// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FMPadding_Batch_0_FMPadding_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [7:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_FMPadding_fu_16_ap_start;
wire    grp_FMPadding_fu_16_ap_done;
wire    grp_FMPadding_fu_16_ap_idle;
wire    grp_FMPadding_fu_16_ap_ready;
wire    grp_FMPadding_fu_16_in_V_V_TREADY;
wire   [7:0] grp_FMPadding_fu_16_out_V_V_TDATA;
wire    grp_FMPadding_fu_16_out_V_V_TVALID;
wire    grp_FMPadding_fu_16_out_V_V_TREADY;
reg    grp_FMPadding_fu_16_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_FMPadding_fu_16_ap_start_reg = 1'b0;
end

FMPadding_Batch_0_FMPadding grp_FMPadding_fu_16(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_FMPadding_fu_16_ap_start),
    .ap_done(grp_FMPadding_fu_16_ap_done),
    .ap_idle(grp_FMPadding_fu_16_ap_idle),
    .ap_ready(grp_FMPadding_fu_16_ap_ready),
    .in_V_V_TDATA(in_V_V_TDATA),
    .in_V_V_TVALID(in_V_V_TVALID),
    .in_V_V_TREADY(grp_FMPadding_fu_16_in_V_V_TREADY),
    .out_V_V_TDATA(grp_FMPadding_fu_16_out_V_V_TDATA),
    .out_V_V_TVALID(grp_FMPadding_fu_16_out_V_V_TVALID),
    .out_V_V_TREADY(grp_FMPadding_fu_16_out_V_V_TREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_FMPadding_fu_16_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_FMPadding_fu_16_ap_start_reg <= 1'b1;
        end else if ((grp_FMPadding_fu_16_ap_ready == 1'b1)) begin
            grp_FMPadding_fu_16_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_FMPadding_fu_16_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_FMPadding_fu_16_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_V_V_TREADY = grp_FMPadding_fu_16_in_V_V_TREADY;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_FMPadding_fu_16_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_FMPadding_fu_16_ap_start = grp_FMPadding_fu_16_ap_start_reg;

assign grp_FMPadding_fu_16_out_V_V_TREADY = (out_V_V_TREADY & ap_CS_fsm_state2);

assign out_V_V_TDATA = grp_FMPadding_fu_16_out_V_V_TDATA;

assign out_V_V_TVALID = grp_FMPadding_fu_16_out_V_V_TVALID;

endmodule //FMPadding_Batch_0_FMPadding_Batch
