// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingFCLayer_Batch_3_Matrix_Vector_Activa (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY,
        weights_m_weights_V_address0,
        weights_m_weights_V_ce0,
        weights_m_weights_V_q0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [7:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;
output  [8:0] weights_m_weights_V_address0;
output   weights_m_weights_V_ce0;
input  [59:0] weights_m_weights_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg out_V_V_TVALID;
reg weights_m_weights_V_ce0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] threshs_m_thresholds_2_address0;
reg    threshs_m_thresholds_2_ce0;
wire   [2:0] threshs_m_thresholds_2_q0;
wire   [5:0] threshs_m_thresholds_1_address0;
reg    threshs_m_thresholds_1_ce0;
wire   [2:0] threshs_m_thresholds_1_q0;
wire   [5:0] threshs_m_thresholds_address0;
reg    threshs_m_thresholds_ce0;
wire   [4:0] threshs_m_thresholds_q0;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln122_fu_326_p2;
wire   [0:0] icmp_ln125_fu_341_p2;
reg    out_V_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln160_reg_2220;
reg   [0:0] icmp_ln160_reg_2220_pp0_iter1_reg;
reg   [8:0] i_0_reg_291;
reg    ap_predicate_op40_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_state4_io;
reg    ap_block_pp0_stage0_11001;
wire   [8:0] i_fu_332_p2;
wire   [59:0] inElem_V_9_fu_369_p7;
wire   [59:0] tmp_V_2_fu_385_p1;
wire   [0:0] icmp_ln137_fu_538_p2;
reg   [0:0] icmp_ln137_reg_2210;
wire   [0:0] icmp_ln160_fu_561_p2;
wire   [9:0] add_ln700_29_fu_2041_p2;
reg   [9:0] add_ln700_29_reg_2239;
reg   [2:0] threshs_m_thresholds_4_reg_2246;
reg   [2:0] threshs_m_thresholds_6_reg_2251;
reg   [4:0] threshs_m_thresholds_8_reg_2256;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire   [59:0] ap_phi_reg_pp0_iter0_act_m_val_V_reg_302;
reg   [59:0] ap_phi_reg_pp0_iter1_act_m_val_V_reg_302;
wire   [63:0] zext_ln137_fu_544_p1;
wire   [63:0] zext_ln186_fu_580_p1;
reg   [9:0] accu_V_0_0_0_fu_190;
reg   [31:0] tile_assign_fu_194;
wire   [31:0] tile_fu_549_p2;
wire   [31:0] tile_1_fu_607_p3;
reg   [31:0] sf_1_fu_198;
wire   [31:0] sf_fu_555_p2;
reg   [31:0] nf_assign_fu_202;
wire   [31:0] nf_1_fu_599_p3;
reg   [59:0] inElem_V_1_fu_206;
wire   [59:0] inElem_V_12_fu_499_p3;
reg   [59:0] inElem_V_3_fu_210;
wire   [59:0] inElem_V_11_fu_491_p3;
reg   [59:0] inElem_V_2_fu_214;
wire   [59:0] inElem_V_8_fu_475_p3;
reg   [59:0] inElem_V_4_fu_218;
wire   [59:0] inElem_V_7_fu_459_p3;
reg   [59:0] inElem_V_5_fu_222;
wire   [59:0] inElem_V_fu_435_p3;
reg    ap_block_pp0_stage0_01001;
wire   [2:0] inElem_V_9_fu_369_p6;
wire   [2:0] trunc_ln321_fu_389_p1;
wire   [0:0] icmp_ln321_3_fu_411_p2;
wire   [0:0] icmp_ln321_2_fu_405_p2;
wire   [0:0] icmp_ln321_1_fu_399_p2;
wire   [0:0] icmp_ln321_fu_393_p2;
wire   [0:0] or_ln321_fu_417_p2;
wire   [0:0] or_ln321_1_fu_423_p2;
wire   [0:0] or_ln321_2_fu_429_p2;
wire   [59:0] select_ln321_fu_443_p3;
wire   [59:0] select_ln321_1_fu_451_p3;
wire   [59:0] select_ln321_3_fu_467_p3;
wire   [59:0] inElem_V_10_fu_483_p3;
wire   [31:0] nf_fu_587_p2;
wire   [0:0] icmp_ln173_fu_593_p2;
wire  signed [1:0] wgt_M_instance_0_V_fu_635_p1;
wire   [1:0] trunc_ln647_fu_929_p1;
wire   [1:0] mul_ln1352_fu_941_p0;
wire  signed [3:0] mul_ln1352_fu_941_p2;
wire  signed [1:0] wgt_M_instance_1_V_fu_639_p4;
wire   [1:0] arg_V_read_assign_1_fu_951_p4;
wire   [1:0] mul_ln1352_1_fu_969_p0;
wire  signed [3:0] mul_ln1352_1_fu_969_p2;
wire  signed [1:0] wgt_M_instance_2_V_fu_649_p4;
wire   [1:0] arg_V_read_assign_2_fu_979_p4;
wire   [1:0] mul_ln1352_2_fu_997_p0;
wire  signed [3:0] mul_ln1352_2_fu_997_p2;
wire  signed [1:0] wgt_M_instance_3_V_fu_659_p4;
wire   [1:0] arg_V_read_assign_3_fu_1007_p4;
wire   [1:0] mul_ln1352_3_fu_1025_p0;
wire  signed [3:0] mul_ln1352_3_fu_1025_p2;
wire  signed [1:0] wgt_M_instance_4_V_fu_669_p4;
wire   [1:0] arg_V_read_assign_4_fu_1035_p4;
wire   [1:0] mul_ln1352_4_fu_1053_p0;
wire  signed [3:0] mul_ln1352_4_fu_1053_p2;
wire  signed [1:0] wgt_M_instance_5_V_fu_679_p4;
wire   [1:0] arg_V_read_assign_5_fu_1063_p4;
wire   [1:0] mul_ln1352_5_fu_1081_p0;
wire  signed [3:0] mul_ln1352_5_fu_1081_p2;
wire  signed [1:0] wgt_M_instance_6_V_fu_689_p4;
wire   [1:0] arg_V_read_assign_6_fu_1091_p4;
wire   [1:0] mul_ln1352_6_fu_1109_p0;
wire  signed [3:0] mul_ln1352_6_fu_1109_p2;
wire  signed [1:0] wgt_M_instance_7_V_fu_699_p4;
wire   [1:0] arg_V_read_assign_7_fu_1119_p4;
wire   [1:0] mul_ln1352_7_fu_1137_p0;
wire  signed [3:0] mul_ln1352_7_fu_1137_p2;
wire  signed [1:0] wgt_M_instance_8_V_fu_709_p4;
wire   [1:0] arg_V_read_assign_8_fu_1147_p4;
wire   [1:0] mul_ln1352_8_fu_1165_p0;
wire  signed [3:0] mul_ln1352_8_fu_1165_p2;
wire  signed [1:0] wgt_M_instance_9_V_fu_719_p4;
wire   [1:0] arg_V_read_assign_9_fu_1175_p4;
wire   [1:0] mul_ln1352_9_fu_1193_p0;
wire  signed [3:0] mul_ln1352_9_fu_1193_p2;
wire  signed [1:0] wgt_M_instance_10_s_fu_729_p4;
wire   [1:0] arg_V_read_assign_s_fu_1203_p4;
wire   [1:0] mul_ln1352_10_fu_1221_p0;
wire  signed [3:0] mul_ln1352_10_fu_1221_p2;
wire  signed [1:0] wgt_M_instance_11_s_fu_739_p4;
wire   [1:0] arg_V_read_assign_10_fu_1231_p4;
wire   [1:0] mul_ln1352_11_fu_1249_p0;
wire  signed [3:0] mul_ln1352_11_fu_1249_p2;
wire  signed [1:0] wgt_M_instance_12_s_fu_749_p4;
wire   [1:0] arg_V_read_assign_11_fu_1259_p4;
wire   [1:0] mul_ln1352_12_fu_1277_p0;
wire  signed [3:0] mul_ln1352_12_fu_1277_p2;
wire  signed [1:0] wgt_M_instance_13_s_fu_759_p4;
wire   [1:0] arg_V_read_assign_12_fu_1287_p4;
wire   [1:0] mul_ln1352_13_fu_1305_p0;
wire  signed [3:0] mul_ln1352_13_fu_1305_p2;
wire  signed [1:0] wgt_M_instance_14_s_fu_769_p4;
wire   [1:0] arg_V_read_assign_13_fu_1315_p4;
wire   [1:0] mul_ln1352_14_fu_1333_p0;
wire  signed [3:0] mul_ln1352_14_fu_1333_p2;
wire  signed [1:0] wgt_M_instance_15_s_fu_779_p4;
wire   [1:0] arg_V_read_assign_14_fu_1343_p4;
wire   [1:0] mul_ln1352_15_fu_1361_p0;
wire  signed [3:0] mul_ln1352_15_fu_1361_p2;
wire  signed [1:0] wgt_M_instance_16_s_fu_789_p4;
wire   [1:0] arg_V_read_assign_15_fu_1371_p4;
wire   [1:0] mul_ln1352_16_fu_1389_p0;
wire  signed [3:0] mul_ln1352_16_fu_1389_p2;
wire  signed [1:0] wgt_M_instance_17_s_fu_799_p4;
wire   [1:0] arg_V_read_assign_16_fu_1399_p4;
wire   [1:0] mul_ln1352_17_fu_1417_p0;
wire  signed [3:0] mul_ln1352_17_fu_1417_p2;
wire  signed [1:0] wgt_M_instance_18_s_fu_809_p4;
wire   [1:0] arg_V_read_assign_17_fu_1427_p4;
wire   [1:0] mul_ln1352_18_fu_1445_p0;
wire  signed [3:0] mul_ln1352_18_fu_1445_p2;
wire  signed [1:0] wgt_M_instance_19_s_fu_819_p4;
wire   [1:0] arg_V_read_assign_18_fu_1455_p4;
wire   [1:0] mul_ln1352_19_fu_1473_p0;
wire  signed [3:0] mul_ln1352_19_fu_1473_p2;
wire  signed [1:0] wgt_M_instance_20_s_fu_829_p4;
wire   [1:0] arg_V_read_assign_19_fu_1483_p4;
wire   [1:0] mul_ln1352_20_fu_1501_p0;
wire  signed [3:0] mul_ln1352_20_fu_1501_p2;
wire  signed [1:0] wgt_M_instance_21_s_fu_839_p4;
wire   [1:0] arg_V_read_assign_20_fu_1511_p4;
wire   [1:0] mul_ln1352_21_fu_1529_p0;
wire  signed [3:0] mul_ln1352_21_fu_1529_p2;
wire  signed [1:0] wgt_M_instance_22_s_fu_849_p4;
wire   [1:0] arg_V_read_assign_21_fu_1539_p4;
wire   [1:0] mul_ln1352_22_fu_1557_p0;
wire  signed [3:0] mul_ln1352_22_fu_1557_p2;
wire  signed [1:0] wgt_M_instance_23_s_fu_859_p4;
wire   [1:0] arg_V_read_assign_22_fu_1567_p4;
wire   [1:0] mul_ln1352_23_fu_1585_p0;
wire  signed [3:0] mul_ln1352_23_fu_1585_p2;
wire  signed [1:0] wgt_M_instance_24_s_fu_869_p4;
wire   [1:0] arg_V_read_assign_23_fu_1595_p4;
wire   [1:0] mul_ln1352_24_fu_1613_p0;
wire  signed [3:0] mul_ln1352_24_fu_1613_p2;
wire  signed [1:0] wgt_M_instance_25_s_fu_879_p4;
wire   [1:0] arg_V_read_assign_24_fu_1623_p4;
wire   [1:0] mul_ln1352_25_fu_1641_p0;
wire  signed [3:0] mul_ln1352_25_fu_1641_p2;
wire  signed [1:0] wgt_M_instance_26_s_fu_889_p4;
wire   [1:0] arg_V_read_assign_25_fu_1651_p4;
wire   [1:0] mul_ln1352_26_fu_1669_p0;
wire  signed [3:0] mul_ln1352_26_fu_1669_p2;
wire  signed [1:0] wgt_M_instance_27_s_fu_899_p4;
wire   [1:0] arg_V_read_assign_26_fu_1679_p4;
wire   [1:0] mul_ln1352_27_fu_1697_p0;
wire  signed [3:0] mul_ln1352_27_fu_1697_p2;
wire  signed [1:0] wgt_M_instance_28_s_fu_909_p4;
wire   [1:0] arg_V_read_assign_27_fu_1707_p4;
wire   [1:0] mul_ln1352_28_fu_1725_p0;
wire  signed [3:0] mul_ln1352_28_fu_1725_p2;
wire  signed [1:0] wgt_M_instance_29_s_fu_919_p4;
wire   [1:0] arg_V_read_assign_28_fu_1735_p4;
wire   [1:0] mul_ln1352_29_fu_1753_p0;
wire  signed [3:0] mul_ln1352_29_fu_1753_p2;
wire  signed [4:0] sext_ln170_28_fu_1731_p1;
wire  signed [4:0] sext_ln170_27_fu_1703_p1;
wire   [4:0] add_ln700_fu_1763_p2;
wire   [9:0] res_V_fu_628_p3;
wire  signed [9:0] sext_ln700_1_fu_1769_p1;
wire  signed [4:0] sext_ln170_25_fu_1647_p1;
wire  signed [4:0] sext_ln170_26_fu_1675_p1;
wire   [4:0] add_ln700_2_fu_1779_p2;
wire  signed [4:0] sext_ln170_21_fu_1535_p1;
wire  signed [4:0] sext_ln170_22_fu_1563_p1;
wire   [4:0] add_ln700_3_fu_1789_p2;
wire  signed [5:0] sext_ln700_2_fu_1785_p1;
wire  signed [5:0] sext_ln700_3_fu_1795_p1;
wire   [5:0] add_ln700_4_fu_1799_p2;
wire   [9:0] add_ln700_1_fu_1773_p2;
wire  signed [9:0] sext_ln700_4_fu_1805_p1;
wire  signed [4:0] sext_ln170_23_fu_1591_p1;
wire  signed [4:0] sext_ln170_24_fu_1619_p1;
wire   [4:0] add_ln700_6_fu_1815_p2;
wire  signed [4:0] sext_ln170_16_fu_1395_p1;
wire  signed [4:0] sext_ln170_14_fu_1339_p1;
wire   [4:0] add_ln700_7_fu_1825_p2;
wire  signed [5:0] sext_ln700_5_fu_1821_p1;
wire  signed [5:0] sext_ln700_6_fu_1831_p1;
wire   [5:0] add_ln700_8_fu_1835_p2;
wire  signed [4:0] sext_ln170_18_fu_1451_p1;
wire  signed [4:0] sext_ln170_15_fu_1367_p1;
wire   [4:0] add_ln700_9_fu_1845_p2;
wire  signed [4:0] sext_ln170_20_fu_1507_p1;
wire  signed [4:0] sext_ln170_17_fu_1423_p1;
wire   [4:0] add_ln700_10_fu_1855_p2;
wire  signed [5:0] sext_ln700_8_fu_1851_p1;
wire  signed [5:0] sext_ln700_9_fu_1861_p1;
wire   [5:0] add_ln700_11_fu_1865_p2;
wire  signed [6:0] sext_ln700_7_fu_1841_p1;
wire  signed [6:0] sext_ln700_10_fu_1871_p1;
wire   [6:0] add_ln700_12_fu_1875_p2;
wire   [9:0] add_ln700_5_fu_1809_p2;
wire  signed [9:0] sext_ln700_11_fu_1881_p1;
wire  signed [4:0] sext_ln170_1_fu_975_p1;
wire  signed [4:0] sext_ln170_19_fu_1479_p1;
wire   [4:0] add_ln700_14_fu_1891_p2;
wire  signed [4:0] sext_ln170_3_fu_1031_p1;
wire  signed [4:0] sext_ln170_fu_947_p1;
wire   [4:0] add_ln700_15_fu_1901_p2;
wire  signed [5:0] sext_ln700_12_fu_1897_p1;
wire  signed [5:0] sext_ln700_13_fu_1907_p1;
wire   [5:0] add_ln700_16_fu_1911_p2;
wire  signed [4:0] sext_ln170_5_fu_1087_p1;
wire  signed [4:0] sext_ln170_2_fu_1003_p1;
wire   [4:0] add_ln700_17_fu_1921_p2;
wire  signed [4:0] sext_ln170_7_fu_1143_p1;
wire  signed [4:0] sext_ln170_4_fu_1059_p1;
wire   [4:0] add_ln700_18_fu_1931_p2;
wire  signed [5:0] sext_ln700_15_fu_1927_p1;
wire  signed [5:0] sext_ln700_16_fu_1937_p1;
wire   [5:0] add_ln700_19_fu_1941_p2;
wire  signed [6:0] sext_ln700_14_fu_1917_p1;
wire  signed [6:0] sext_ln700_17_fu_1947_p1;
wire   [6:0] add_ln700_20_fu_1951_p2;
wire  signed [4:0] sext_ln170_9_fu_1199_p1;
wire  signed [4:0] sext_ln170_6_fu_1115_p1;
wire   [4:0] add_ln700_21_fu_1961_p2;
wire  signed [4:0] sext_ln170_11_fu_1255_p1;
wire  signed [4:0] sext_ln170_8_fu_1171_p1;
wire   [4:0] add_ln700_22_fu_1971_p2;
wire  signed [5:0] sext_ln700_19_fu_1967_p1;
wire  signed [5:0] sext_ln700_20_fu_1977_p1;
wire   [5:0] add_ln700_23_fu_1981_p2;
wire  signed [4:0] sext_ln170_13_fu_1311_p1;
wire  signed [4:0] sext_ln170_10_fu_1227_p1;
wire   [4:0] add_ln700_24_fu_1991_p2;
wire  signed [4:0] sext_ln700_fu_1759_p1;
wire  signed [4:0] sext_ln170_12_fu_1283_p1;
wire   [4:0] add_ln700_25_fu_2001_p2;
wire  signed [5:0] sext_ln700_22_fu_1997_p1;
wire  signed [5:0] sext_ln700_23_fu_2007_p1;
wire   [5:0] add_ln700_26_fu_2011_p2;
wire  signed [6:0] sext_ln700_21_fu_1987_p1;
wire  signed [6:0] sext_ln700_24_fu_2017_p1;
wire   [6:0] add_ln700_27_fu_2021_p2;
wire  signed [7:0] sext_ln700_18_fu_1957_p1;
wire  signed [7:0] sext_ln700_25_fu_2027_p1;
wire   [7:0] add_ln700_28_fu_2031_p2;
wire   [9:0] add_ln700_13_fu_1885_p2;
wire  signed [9:0] sext_ln700_26_fu_2037_p1;
wire   [9:0] zext_ln186_1_fu_2052_p1;
wire   [0:0] icmp_ln899_fu_2055_p2;
wire   [0:0] xor_ln899_fu_2060_p2;
wire  signed [3:0] sext_ln186_fu_2070_p1;
wire   [9:0] zext_ln186_2_fu_2073_p1;
wire   [0:0] icmp_ln899_1_fu_2077_p2;
wire   [0:0] xor_ln899_1_fu_2082_p2;
wire   [9:0] zext_ln186_3_fu_2092_p1;
wire   [0:0] icmp_ln899_2_fu_2095_p2;
wire   [0:0] xor_ln899_2_fu_2100_p2;
wire   [1:0] zext_ln700_1_fu_2088_p1;
wire   [1:0] zext_ln700_2_fu_2106_p1;
wire   [1:0] add_ln700_30_fu_2110_p2;
wire   [1:0] zext_ln700_fu_2066_p1;
wire   [1:0] tmp_V_fu_2116_p2;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [3:0] mul_ln1352_10_fu_1221_p00;
wire   [3:0] mul_ln1352_11_fu_1249_p00;
wire   [3:0] mul_ln1352_12_fu_1277_p00;
wire   [3:0] mul_ln1352_13_fu_1305_p00;
wire   [3:0] mul_ln1352_14_fu_1333_p00;
wire   [3:0] mul_ln1352_15_fu_1361_p00;
wire   [3:0] mul_ln1352_16_fu_1389_p00;
wire   [3:0] mul_ln1352_17_fu_1417_p00;
wire   [3:0] mul_ln1352_18_fu_1445_p00;
wire   [3:0] mul_ln1352_19_fu_1473_p00;
wire   [3:0] mul_ln1352_1_fu_969_p00;
wire   [3:0] mul_ln1352_20_fu_1501_p00;
wire   [3:0] mul_ln1352_21_fu_1529_p00;
wire   [3:0] mul_ln1352_22_fu_1557_p00;
wire   [3:0] mul_ln1352_23_fu_1585_p00;
wire   [3:0] mul_ln1352_24_fu_1613_p00;
wire   [3:0] mul_ln1352_25_fu_1641_p00;
wire   [3:0] mul_ln1352_26_fu_1669_p00;
wire   [3:0] mul_ln1352_27_fu_1697_p00;
wire   [3:0] mul_ln1352_28_fu_1725_p00;
wire   [3:0] mul_ln1352_29_fu_1753_p00;
wire   [3:0] mul_ln1352_2_fu_997_p00;
wire   [3:0] mul_ln1352_3_fu_1025_p00;
wire   [3:0] mul_ln1352_4_fu_1053_p00;
wire   [3:0] mul_ln1352_5_fu_1081_p00;
wire   [3:0] mul_ln1352_6_fu_1109_p00;
wire   [3:0] mul_ln1352_7_fu_1137_p00;
wire   [3:0] mul_ln1352_8_fu_1165_p00;
wire   [3:0] mul_ln1352_9_fu_1193_p00;
wire   [3:0] mul_ln1352_fu_941_p00;
reg    ap_condition_112;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

StreamingFCLayer_Batch_3_Matrix_Vector_Actbkb #(
    .DataWidth( 3 ),
    .AddressRange( 60 ),
    .AddressWidth( 6 ))
threshs_m_thresholds_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_2_address0),
    .ce0(threshs_m_thresholds_2_ce0),
    .q0(threshs_m_thresholds_2_q0)
);

StreamingFCLayer_Batch_3_Matrix_Vector_Actbkb #(
    .DataWidth( 3 ),
    .AddressRange( 60 ),
    .AddressWidth( 6 ))
threshs_m_thresholds_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_1_address0),
    .ce0(threshs_m_thresholds_1_ce0),
    .q0(threshs_m_thresholds_1_q0)
);

StreamingFCLayer_Batch_3_Matrix_Vector_ActdEe #(
    .DataWidth( 5 ),
    .AddressRange( 60 ),
    .AddressWidth( 6 ))
threshs_m_thresholds_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_address0),
    .ce0(threshs_m_thresholds_ce0),
    .q0(threshs_m_thresholds_q0)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 60 ),
    .din1_WIDTH( 60 ),
    .din2_WIDTH( 60 ),
    .din3_WIDTH( 60 ),
    .din4_WIDTH( 60 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 60 ))
StreamingFCLayer_eOg_U1(
    .din0(inElem_V_1_fu_206),
    .din1(inElem_V_3_fu_210),
    .din2(inElem_V_2_fu_214),
    .din3(inElem_V_4_fu_218),
    .din4(inElem_V_5_fu_222),
    .din5(inElem_V_9_fu_369_p6),
    .dout(inElem_V_9_fu_369_p7)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U2(
    .din0(mul_ln1352_fu_941_p0),
    .din1(wgt_M_instance_0_V_fu_635_p1),
    .dout(mul_ln1352_fu_941_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U3(
    .din0(mul_ln1352_1_fu_969_p0),
    .din1(wgt_M_instance_1_V_fu_639_p4),
    .dout(mul_ln1352_1_fu_969_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U4(
    .din0(mul_ln1352_2_fu_997_p0),
    .din1(wgt_M_instance_2_V_fu_649_p4),
    .dout(mul_ln1352_2_fu_997_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U5(
    .din0(mul_ln1352_3_fu_1025_p0),
    .din1(wgt_M_instance_3_V_fu_659_p4),
    .dout(mul_ln1352_3_fu_1025_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U6(
    .din0(mul_ln1352_4_fu_1053_p0),
    .din1(wgt_M_instance_4_V_fu_669_p4),
    .dout(mul_ln1352_4_fu_1053_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U7(
    .din0(mul_ln1352_5_fu_1081_p0),
    .din1(wgt_M_instance_5_V_fu_679_p4),
    .dout(mul_ln1352_5_fu_1081_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U8(
    .din0(mul_ln1352_6_fu_1109_p0),
    .din1(wgt_M_instance_6_V_fu_689_p4),
    .dout(mul_ln1352_6_fu_1109_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U9(
    .din0(mul_ln1352_7_fu_1137_p0),
    .din1(wgt_M_instance_7_V_fu_699_p4),
    .dout(mul_ln1352_7_fu_1137_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U10(
    .din0(mul_ln1352_8_fu_1165_p0),
    .din1(wgt_M_instance_8_V_fu_709_p4),
    .dout(mul_ln1352_8_fu_1165_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U11(
    .din0(mul_ln1352_9_fu_1193_p0),
    .din1(wgt_M_instance_9_V_fu_719_p4),
    .dout(mul_ln1352_9_fu_1193_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U12(
    .din0(mul_ln1352_10_fu_1221_p0),
    .din1(wgt_M_instance_10_s_fu_729_p4),
    .dout(mul_ln1352_10_fu_1221_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U13(
    .din0(mul_ln1352_11_fu_1249_p0),
    .din1(wgt_M_instance_11_s_fu_739_p4),
    .dout(mul_ln1352_11_fu_1249_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U14(
    .din0(mul_ln1352_12_fu_1277_p0),
    .din1(wgt_M_instance_12_s_fu_749_p4),
    .dout(mul_ln1352_12_fu_1277_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U15(
    .din0(mul_ln1352_13_fu_1305_p0),
    .din1(wgt_M_instance_13_s_fu_759_p4),
    .dout(mul_ln1352_13_fu_1305_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U16(
    .din0(mul_ln1352_14_fu_1333_p0),
    .din1(wgt_M_instance_14_s_fu_769_p4),
    .dout(mul_ln1352_14_fu_1333_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U17(
    .din0(mul_ln1352_15_fu_1361_p0),
    .din1(wgt_M_instance_15_s_fu_779_p4),
    .dout(mul_ln1352_15_fu_1361_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U18(
    .din0(mul_ln1352_16_fu_1389_p0),
    .din1(wgt_M_instance_16_s_fu_789_p4),
    .dout(mul_ln1352_16_fu_1389_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U19(
    .din0(mul_ln1352_17_fu_1417_p0),
    .din1(wgt_M_instance_17_s_fu_799_p4),
    .dout(mul_ln1352_17_fu_1417_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U20(
    .din0(mul_ln1352_18_fu_1445_p0),
    .din1(wgt_M_instance_18_s_fu_809_p4),
    .dout(mul_ln1352_18_fu_1445_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U21(
    .din0(mul_ln1352_19_fu_1473_p0),
    .din1(wgt_M_instance_19_s_fu_819_p4),
    .dout(mul_ln1352_19_fu_1473_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U22(
    .din0(mul_ln1352_20_fu_1501_p0),
    .din1(wgt_M_instance_20_s_fu_829_p4),
    .dout(mul_ln1352_20_fu_1501_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U23(
    .din0(mul_ln1352_21_fu_1529_p0),
    .din1(wgt_M_instance_21_s_fu_839_p4),
    .dout(mul_ln1352_21_fu_1529_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U24(
    .din0(mul_ln1352_22_fu_1557_p0),
    .din1(wgt_M_instance_22_s_fu_849_p4),
    .dout(mul_ln1352_22_fu_1557_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U25(
    .din0(mul_ln1352_23_fu_1585_p0),
    .din1(wgt_M_instance_23_s_fu_859_p4),
    .dout(mul_ln1352_23_fu_1585_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U26(
    .din0(mul_ln1352_24_fu_1613_p0),
    .din1(wgt_M_instance_24_s_fu_869_p4),
    .dout(mul_ln1352_24_fu_1613_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U27(
    .din0(mul_ln1352_25_fu_1641_p0),
    .din1(wgt_M_instance_25_s_fu_879_p4),
    .dout(mul_ln1352_25_fu_1641_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U28(
    .din0(mul_ln1352_26_fu_1669_p0),
    .din1(wgt_M_instance_26_s_fu_889_p4),
    .dout(mul_ln1352_26_fu_1669_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U29(
    .din0(mul_ln1352_27_fu_1697_p0),
    .din1(wgt_M_instance_27_s_fu_899_p4),
    .dout(mul_ln1352_27_fu_1697_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U30(
    .din0(mul_ln1352_28_fu_1725_p0),
    .din1(wgt_M_instance_28_s_fu_909_p4),
    .dout(mul_ln1352_28_fu_1725_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U31(
    .din0(mul_ln1352_29_fu_1753_p0),
    .din1(wgt_M_instance_29_s_fu_919_p4),
    .dout(mul_ln1352_29_fu_1753_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_112)) begin
        if (((icmp_ln125_fu_341_p2 == 1'd0) & (icmp_ln122_fu_326_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_act_m_val_V_reg_302 <= inElem_V_9_fu_369_p7;
        end else if (((icmp_ln125_fu_341_p2 == 1'd1) & (icmp_ln122_fu_326_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_act_m_val_V_reg_302 <= tmp_V_2_fu_385_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_act_m_val_V_reg_302 <= ap_phi_reg_pp0_iter0_act_m_val_V_reg_302;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln122_fu_326_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_0_reg_291 <= i_fu_332_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_291 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln160_fu_561_p2 == 1'd1) & (icmp_ln122_fu_326_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nf_assign_fu_202 <= nf_1_fu_599_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nf_assign_fu_202 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln160_fu_561_p2 == 1'd0) & (icmp_ln122_fu_326_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sf_1_fu_198 <= sf_fu_555_p2;
    end else if ((((icmp_ln160_fu_561_p2 == 1'd1) & (icmp_ln122_fu_326_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sf_1_fu_198 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln160_fu_561_p2 == 1'd1) & (icmp_ln122_fu_326_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tile_assign_fu_194 <= tile_1_fu_607_p3;
    end else if (((icmp_ln160_fu_561_p2 == 1'd0) & (icmp_ln122_fu_326_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tile_assign_fu_194 <= tile_fu_549_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_assign_fu_194 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        accu_V_0_0_0_fu_190 <= add_ln700_29_fu_2041_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln700_29_reg_2239 <= add_ln700_29_fu_2041_p2;
        icmp_ln160_reg_2220_pp0_iter1_reg <= icmp_ln160_reg_2220;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln122_fu_326_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln137_reg_2210 <= icmp_ln137_fu_538_p2;
        icmp_ln160_reg_2220 <= icmp_ln160_fu_561_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln125_fu_341_p2 == 1'd1) & (icmp_ln122_fu_326_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inElem_V_1_fu_206 <= inElem_V_12_fu_499_p3;
        inElem_V_2_fu_214 <= inElem_V_8_fu_475_p3;
        inElem_V_3_fu_210 <= inElem_V_11_fu_491_p3;
        inElem_V_4_fu_218 <= inElem_V_7_fu_459_p3;
        inElem_V_5_fu_222 <= inElem_V_fu_435_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln160_reg_2220 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_4_reg_2246 <= threshs_m_thresholds_2_q0;
        threshs_m_thresholds_6_reg_2251 <= threshs_m_thresholds_1_q0;
        threshs_m_thresholds_8_reg_2256 <= threshs_m_thresholds_q0;
    end
end

always @ (*) begin
    if ((icmp_ln122_fu_326_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln125_fu_341_p2 == 1'd1) & (icmp_ln122_fu_326_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_V_V_TDATA_blk_n = in_V_V_TVALID;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op40_read_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_reg_2220_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_V_V_TDATA_blk_n = out_V_V_TREADY;
    end else begin
        out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln160_reg_2220_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_V_V_TVALID = 1'b1;
    end else begin
        out_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_1_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_2_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights_m_weights_V_ce0 = 1'b1;
    end else begin
        weights_m_weights_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln122_fu_326_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((icmp_ln122_fu_326_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln700_10_fu_1855_p2 = ($signed(sext_ln170_20_fu_1507_p1) + $signed(sext_ln170_17_fu_1423_p1));

assign add_ln700_11_fu_1865_p2 = ($signed(sext_ln700_8_fu_1851_p1) + $signed(sext_ln700_9_fu_1861_p1));

assign add_ln700_12_fu_1875_p2 = ($signed(sext_ln700_7_fu_1841_p1) + $signed(sext_ln700_10_fu_1871_p1));

assign add_ln700_13_fu_1885_p2 = ($signed(add_ln700_5_fu_1809_p2) + $signed(sext_ln700_11_fu_1881_p1));

assign add_ln700_14_fu_1891_p2 = ($signed(sext_ln170_1_fu_975_p1) + $signed(sext_ln170_19_fu_1479_p1));

assign add_ln700_15_fu_1901_p2 = ($signed(sext_ln170_3_fu_1031_p1) + $signed(sext_ln170_fu_947_p1));

assign add_ln700_16_fu_1911_p2 = ($signed(sext_ln700_12_fu_1897_p1) + $signed(sext_ln700_13_fu_1907_p1));

assign add_ln700_17_fu_1921_p2 = ($signed(sext_ln170_5_fu_1087_p1) + $signed(sext_ln170_2_fu_1003_p1));

assign add_ln700_18_fu_1931_p2 = ($signed(sext_ln170_7_fu_1143_p1) + $signed(sext_ln170_4_fu_1059_p1));

assign add_ln700_19_fu_1941_p2 = ($signed(sext_ln700_15_fu_1927_p1) + $signed(sext_ln700_16_fu_1937_p1));

assign add_ln700_1_fu_1773_p2 = ($signed(res_V_fu_628_p3) + $signed(sext_ln700_1_fu_1769_p1));

assign add_ln700_20_fu_1951_p2 = ($signed(sext_ln700_14_fu_1917_p1) + $signed(sext_ln700_17_fu_1947_p1));

assign add_ln700_21_fu_1961_p2 = ($signed(sext_ln170_9_fu_1199_p1) + $signed(sext_ln170_6_fu_1115_p1));

assign add_ln700_22_fu_1971_p2 = ($signed(sext_ln170_11_fu_1255_p1) + $signed(sext_ln170_8_fu_1171_p1));

assign add_ln700_23_fu_1981_p2 = ($signed(sext_ln700_19_fu_1967_p1) + $signed(sext_ln700_20_fu_1977_p1));

assign add_ln700_24_fu_1991_p2 = ($signed(sext_ln170_13_fu_1311_p1) + $signed(sext_ln170_10_fu_1227_p1));

assign add_ln700_25_fu_2001_p2 = ($signed(sext_ln700_fu_1759_p1) + $signed(sext_ln170_12_fu_1283_p1));

assign add_ln700_26_fu_2011_p2 = ($signed(sext_ln700_22_fu_1997_p1) + $signed(sext_ln700_23_fu_2007_p1));

assign add_ln700_27_fu_2021_p2 = ($signed(sext_ln700_21_fu_1987_p1) + $signed(sext_ln700_24_fu_2017_p1));

assign add_ln700_28_fu_2031_p2 = ($signed(sext_ln700_18_fu_1957_p1) + $signed(sext_ln700_25_fu_2027_p1));

assign add_ln700_29_fu_2041_p2 = ($signed(add_ln700_13_fu_1885_p2) + $signed(sext_ln700_26_fu_2037_p1));

assign add_ln700_2_fu_1779_p2 = ($signed(sext_ln170_25_fu_1647_p1) + $signed(sext_ln170_26_fu_1675_p1));

assign add_ln700_30_fu_2110_p2 = (zext_ln700_1_fu_2088_p1 + zext_ln700_2_fu_2106_p1);

assign add_ln700_3_fu_1789_p2 = ($signed(sext_ln170_21_fu_1535_p1) + $signed(sext_ln170_22_fu_1563_p1));

assign add_ln700_4_fu_1799_p2 = ($signed(sext_ln700_2_fu_1785_p1) + $signed(sext_ln700_3_fu_1795_p1));

assign add_ln700_5_fu_1809_p2 = ($signed(add_ln700_1_fu_1773_p2) + $signed(sext_ln700_4_fu_1805_p1));

assign add_ln700_6_fu_1815_p2 = ($signed(sext_ln170_23_fu_1591_p1) + $signed(sext_ln170_24_fu_1619_p1));

assign add_ln700_7_fu_1825_p2 = ($signed(sext_ln170_16_fu_1395_p1) + $signed(sext_ln170_14_fu_1339_p1));

assign add_ln700_8_fu_1835_p2 = ($signed(sext_ln700_5_fu_1821_p1) + $signed(sext_ln700_6_fu_1831_p1));

assign add_ln700_9_fu_1845_p2 = ($signed(sext_ln170_18_fu_1451_p1) + $signed(sext_ln170_15_fu_1367_p1));

assign add_ln700_fu_1763_p2 = ($signed(sext_ln170_28_fu_1731_p1) + $signed(sext_ln170_27_fu_1703_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((in_V_V_TVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op40_read_state2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((in_V_V_TVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op40_read_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((in_V_V_TVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op40_read_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((in_V_V_TVALID == 1'b0) & (ap_predicate_op40_read_state2 == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((icmp_ln160_reg_2220_pp0_iter1_reg == 1'd1) & (out_V_V_TREADY == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_112 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_act_m_val_V_reg_302 = 'bx;

always @ (*) begin
    ap_predicate_op40_read_state2 = ((icmp_ln125_fu_341_p2 == 1'd1) & (icmp_ln122_fu_326_p2 == 1'd0));
end

assign arg_V_read_assign_10_fu_1231_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[23:22]}};

assign arg_V_read_assign_11_fu_1259_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[25:24]}};

assign arg_V_read_assign_12_fu_1287_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[27:26]}};

assign arg_V_read_assign_13_fu_1315_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[29:28]}};

assign arg_V_read_assign_14_fu_1343_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[31:30]}};

assign arg_V_read_assign_15_fu_1371_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[33:32]}};

assign arg_V_read_assign_16_fu_1399_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[35:34]}};

assign arg_V_read_assign_17_fu_1427_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[37:36]}};

assign arg_V_read_assign_18_fu_1455_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[39:38]}};

assign arg_V_read_assign_19_fu_1483_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[41:40]}};

assign arg_V_read_assign_1_fu_951_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[3:2]}};

assign arg_V_read_assign_20_fu_1511_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[43:42]}};

assign arg_V_read_assign_21_fu_1539_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[45:44]}};

assign arg_V_read_assign_22_fu_1567_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[47:46]}};

assign arg_V_read_assign_23_fu_1595_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[49:48]}};

assign arg_V_read_assign_24_fu_1623_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[51:50]}};

assign arg_V_read_assign_25_fu_1651_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[53:52]}};

assign arg_V_read_assign_26_fu_1679_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[55:54]}};

assign arg_V_read_assign_27_fu_1707_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[57:56]}};

assign arg_V_read_assign_28_fu_1735_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[59:58]}};

assign arg_V_read_assign_2_fu_979_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[5:4]}};

assign arg_V_read_assign_3_fu_1007_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[7:6]}};

assign arg_V_read_assign_4_fu_1035_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[9:8]}};

assign arg_V_read_assign_5_fu_1063_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[11:10]}};

assign arg_V_read_assign_6_fu_1091_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[13:12]}};

assign arg_V_read_assign_7_fu_1119_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[15:14]}};

assign arg_V_read_assign_8_fu_1147_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[17:16]}};

assign arg_V_read_assign_9_fu_1175_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[19:18]}};

assign arg_V_read_assign_s_fu_1203_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[21:20]}};

assign i_fu_332_p2 = (i_0_reg_291 + 9'd1);

assign icmp_ln122_fu_326_p2 = ((i_0_reg_291 == 9'd300) ? 1'b1 : 1'b0);

assign icmp_ln125_fu_341_p2 = ((nf_assign_fu_202 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln137_fu_538_p2 = ((sf_1_fu_198 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln160_fu_561_p2 = ((sf_fu_555_p2 == 32'd5) ? 1'b1 : 1'b0);

assign icmp_ln173_fu_593_p2 = ((nf_fu_587_p2 == 32'd60) ? 1'b1 : 1'b0);

assign icmp_ln321_1_fu_399_p2 = ((trunc_ln321_fu_389_p1 == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln321_2_fu_405_p2 = ((trunc_ln321_fu_389_p1 == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln321_3_fu_411_p2 = ((trunc_ln321_fu_389_p1 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln321_fu_393_p2 = ((trunc_ln321_fu_389_p1 == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln899_1_fu_2077_p2 = (($signed(add_ln700_29_reg_2239) < $signed(zext_ln186_2_fu_2073_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_2_fu_2095_p2 = (($signed(add_ln700_29_reg_2239) < $signed(zext_ln186_3_fu_2092_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_fu_2055_p2 = (($signed(add_ln700_29_reg_2239) < $signed(zext_ln186_1_fu_2052_p1)) ? 1'b1 : 1'b0);

assign inElem_V_10_fu_483_p3 = ((icmp_ln321_2_fu_405_p2[0:0] === 1'b1) ? tmp_V_2_fu_385_p1 : inElem_V_3_fu_210);

assign inElem_V_11_fu_491_p3 = ((icmp_ln321_3_fu_411_p2[0:0] === 1'b1) ? inElem_V_3_fu_210 : inElem_V_10_fu_483_p3);

assign inElem_V_12_fu_499_p3 = ((icmp_ln321_3_fu_411_p2[0:0] === 1'b1) ? tmp_V_2_fu_385_p1 : inElem_V_1_fu_206);

assign inElem_V_7_fu_459_p3 = ((or_ln321_2_fu_429_p2[0:0] === 1'b1) ? select_ln321_1_fu_451_p3 : inElem_V_4_fu_218);

assign inElem_V_8_fu_475_p3 = ((or_ln321_fu_417_p2[0:0] === 1'b1) ? inElem_V_2_fu_214 : select_ln321_3_fu_467_p3);

assign inElem_V_9_fu_369_p6 = sf_1_fu_198[2:0];

assign inElem_V_fu_435_p3 = ((or_ln321_2_fu_429_p2[0:0] === 1'b1) ? inElem_V_5_fu_222 : tmp_V_2_fu_385_p1);

assign mul_ln1352_10_fu_1221_p0 = mul_ln1352_10_fu_1221_p00;

assign mul_ln1352_10_fu_1221_p00 = arg_V_read_assign_s_fu_1203_p4;

assign mul_ln1352_11_fu_1249_p0 = mul_ln1352_11_fu_1249_p00;

assign mul_ln1352_11_fu_1249_p00 = arg_V_read_assign_10_fu_1231_p4;

assign mul_ln1352_12_fu_1277_p0 = mul_ln1352_12_fu_1277_p00;

assign mul_ln1352_12_fu_1277_p00 = arg_V_read_assign_11_fu_1259_p4;

assign mul_ln1352_13_fu_1305_p0 = mul_ln1352_13_fu_1305_p00;

assign mul_ln1352_13_fu_1305_p00 = arg_V_read_assign_12_fu_1287_p4;

assign mul_ln1352_14_fu_1333_p0 = mul_ln1352_14_fu_1333_p00;

assign mul_ln1352_14_fu_1333_p00 = arg_V_read_assign_13_fu_1315_p4;

assign mul_ln1352_15_fu_1361_p0 = mul_ln1352_15_fu_1361_p00;

assign mul_ln1352_15_fu_1361_p00 = arg_V_read_assign_14_fu_1343_p4;

assign mul_ln1352_16_fu_1389_p0 = mul_ln1352_16_fu_1389_p00;

assign mul_ln1352_16_fu_1389_p00 = arg_V_read_assign_15_fu_1371_p4;

assign mul_ln1352_17_fu_1417_p0 = mul_ln1352_17_fu_1417_p00;

assign mul_ln1352_17_fu_1417_p00 = arg_V_read_assign_16_fu_1399_p4;

assign mul_ln1352_18_fu_1445_p0 = mul_ln1352_18_fu_1445_p00;

assign mul_ln1352_18_fu_1445_p00 = arg_V_read_assign_17_fu_1427_p4;

assign mul_ln1352_19_fu_1473_p0 = mul_ln1352_19_fu_1473_p00;

assign mul_ln1352_19_fu_1473_p00 = arg_V_read_assign_18_fu_1455_p4;

assign mul_ln1352_1_fu_969_p0 = mul_ln1352_1_fu_969_p00;

assign mul_ln1352_1_fu_969_p00 = arg_V_read_assign_1_fu_951_p4;

assign mul_ln1352_20_fu_1501_p0 = mul_ln1352_20_fu_1501_p00;

assign mul_ln1352_20_fu_1501_p00 = arg_V_read_assign_19_fu_1483_p4;

assign mul_ln1352_21_fu_1529_p0 = mul_ln1352_21_fu_1529_p00;

assign mul_ln1352_21_fu_1529_p00 = arg_V_read_assign_20_fu_1511_p4;

assign mul_ln1352_22_fu_1557_p0 = mul_ln1352_22_fu_1557_p00;

assign mul_ln1352_22_fu_1557_p00 = arg_V_read_assign_21_fu_1539_p4;

assign mul_ln1352_23_fu_1585_p0 = mul_ln1352_23_fu_1585_p00;

assign mul_ln1352_23_fu_1585_p00 = arg_V_read_assign_22_fu_1567_p4;

assign mul_ln1352_24_fu_1613_p0 = mul_ln1352_24_fu_1613_p00;

assign mul_ln1352_24_fu_1613_p00 = arg_V_read_assign_23_fu_1595_p4;

assign mul_ln1352_25_fu_1641_p0 = mul_ln1352_25_fu_1641_p00;

assign mul_ln1352_25_fu_1641_p00 = arg_V_read_assign_24_fu_1623_p4;

assign mul_ln1352_26_fu_1669_p0 = mul_ln1352_26_fu_1669_p00;

assign mul_ln1352_26_fu_1669_p00 = arg_V_read_assign_25_fu_1651_p4;

assign mul_ln1352_27_fu_1697_p0 = mul_ln1352_27_fu_1697_p00;

assign mul_ln1352_27_fu_1697_p00 = arg_V_read_assign_26_fu_1679_p4;

assign mul_ln1352_28_fu_1725_p0 = mul_ln1352_28_fu_1725_p00;

assign mul_ln1352_28_fu_1725_p00 = arg_V_read_assign_27_fu_1707_p4;

assign mul_ln1352_29_fu_1753_p0 = mul_ln1352_29_fu_1753_p00;

assign mul_ln1352_29_fu_1753_p00 = arg_V_read_assign_28_fu_1735_p4;

assign mul_ln1352_2_fu_997_p0 = mul_ln1352_2_fu_997_p00;

assign mul_ln1352_2_fu_997_p00 = arg_V_read_assign_2_fu_979_p4;

assign mul_ln1352_3_fu_1025_p0 = mul_ln1352_3_fu_1025_p00;

assign mul_ln1352_3_fu_1025_p00 = arg_V_read_assign_3_fu_1007_p4;

assign mul_ln1352_4_fu_1053_p0 = mul_ln1352_4_fu_1053_p00;

assign mul_ln1352_4_fu_1053_p00 = arg_V_read_assign_4_fu_1035_p4;

assign mul_ln1352_5_fu_1081_p0 = mul_ln1352_5_fu_1081_p00;

assign mul_ln1352_5_fu_1081_p00 = arg_V_read_assign_5_fu_1063_p4;

assign mul_ln1352_6_fu_1109_p0 = mul_ln1352_6_fu_1109_p00;

assign mul_ln1352_6_fu_1109_p00 = arg_V_read_assign_6_fu_1091_p4;

assign mul_ln1352_7_fu_1137_p0 = mul_ln1352_7_fu_1137_p00;

assign mul_ln1352_7_fu_1137_p00 = arg_V_read_assign_7_fu_1119_p4;

assign mul_ln1352_8_fu_1165_p0 = mul_ln1352_8_fu_1165_p00;

assign mul_ln1352_8_fu_1165_p00 = arg_V_read_assign_8_fu_1147_p4;

assign mul_ln1352_9_fu_1193_p0 = mul_ln1352_9_fu_1193_p00;

assign mul_ln1352_9_fu_1193_p00 = arg_V_read_assign_9_fu_1175_p4;

assign mul_ln1352_fu_941_p0 = mul_ln1352_fu_941_p00;

assign mul_ln1352_fu_941_p00 = trunc_ln647_fu_929_p1;

assign nf_1_fu_599_p3 = ((icmp_ln173_fu_593_p2[0:0] === 1'b1) ? 32'd0 : nf_fu_587_p2);

assign nf_fu_587_p2 = (nf_assign_fu_202 + 32'd1);

assign or_ln321_1_fu_423_p2 = (icmp_ln321_fu_393_p2 | icmp_ln321_1_fu_399_p2);

assign or_ln321_2_fu_429_p2 = (or_ln321_fu_417_p2 | or_ln321_1_fu_423_p2);

assign or_ln321_fu_417_p2 = (icmp_ln321_3_fu_411_p2 | icmp_ln321_2_fu_405_p2);

assign out_V_V_TDATA = tmp_V_fu_2116_p2;

assign res_V_fu_628_p3 = ((icmp_ln137_reg_2210[0:0] === 1'b1) ? 10'd0 : accu_V_0_0_0_fu_190);

assign select_ln321_1_fu_451_p3 = ((or_ln321_fu_417_p2[0:0] === 1'b1) ? inElem_V_4_fu_218 : select_ln321_fu_443_p3);

assign select_ln321_3_fu_467_p3 = ((icmp_ln321_1_fu_399_p2[0:0] === 1'b1) ? tmp_V_2_fu_385_p1 : inElem_V_2_fu_214);

assign select_ln321_fu_443_p3 = ((icmp_ln321_1_fu_399_p2[0:0] === 1'b1) ? inElem_V_4_fu_218 : tmp_V_2_fu_385_p1);

assign sext_ln170_10_fu_1227_p1 = mul_ln1352_10_fu_1221_p2;

assign sext_ln170_11_fu_1255_p1 = mul_ln1352_11_fu_1249_p2;

assign sext_ln170_12_fu_1283_p1 = mul_ln1352_12_fu_1277_p2;

assign sext_ln170_13_fu_1311_p1 = mul_ln1352_13_fu_1305_p2;

assign sext_ln170_14_fu_1339_p1 = mul_ln1352_14_fu_1333_p2;

assign sext_ln170_15_fu_1367_p1 = mul_ln1352_15_fu_1361_p2;

assign sext_ln170_16_fu_1395_p1 = mul_ln1352_16_fu_1389_p2;

assign sext_ln170_17_fu_1423_p1 = mul_ln1352_17_fu_1417_p2;

assign sext_ln170_18_fu_1451_p1 = mul_ln1352_18_fu_1445_p2;

assign sext_ln170_19_fu_1479_p1 = mul_ln1352_19_fu_1473_p2;

assign sext_ln170_1_fu_975_p1 = mul_ln1352_1_fu_969_p2;

assign sext_ln170_20_fu_1507_p1 = mul_ln1352_20_fu_1501_p2;

assign sext_ln170_21_fu_1535_p1 = mul_ln1352_21_fu_1529_p2;

assign sext_ln170_22_fu_1563_p1 = mul_ln1352_22_fu_1557_p2;

assign sext_ln170_23_fu_1591_p1 = mul_ln1352_23_fu_1585_p2;

assign sext_ln170_24_fu_1619_p1 = mul_ln1352_24_fu_1613_p2;

assign sext_ln170_25_fu_1647_p1 = mul_ln1352_25_fu_1641_p2;

assign sext_ln170_26_fu_1675_p1 = mul_ln1352_26_fu_1669_p2;

assign sext_ln170_27_fu_1703_p1 = mul_ln1352_27_fu_1697_p2;

assign sext_ln170_28_fu_1731_p1 = mul_ln1352_28_fu_1725_p2;

assign sext_ln170_2_fu_1003_p1 = mul_ln1352_2_fu_997_p2;

assign sext_ln170_3_fu_1031_p1 = mul_ln1352_3_fu_1025_p2;

assign sext_ln170_4_fu_1059_p1 = mul_ln1352_4_fu_1053_p2;

assign sext_ln170_5_fu_1087_p1 = mul_ln1352_5_fu_1081_p2;

assign sext_ln170_6_fu_1115_p1 = mul_ln1352_6_fu_1109_p2;

assign sext_ln170_7_fu_1143_p1 = mul_ln1352_7_fu_1137_p2;

assign sext_ln170_8_fu_1171_p1 = mul_ln1352_8_fu_1165_p2;

assign sext_ln170_9_fu_1199_p1 = mul_ln1352_9_fu_1193_p2;

assign sext_ln170_fu_947_p1 = mul_ln1352_fu_941_p2;

assign sext_ln186_fu_2070_p1 = $signed(threshs_m_thresholds_6_reg_2251);

assign sext_ln700_10_fu_1871_p1 = $signed(add_ln700_11_fu_1865_p2);

assign sext_ln700_11_fu_1881_p1 = $signed(add_ln700_12_fu_1875_p2);

assign sext_ln700_12_fu_1897_p1 = $signed(add_ln700_14_fu_1891_p2);

assign sext_ln700_13_fu_1907_p1 = $signed(add_ln700_15_fu_1901_p2);

assign sext_ln700_14_fu_1917_p1 = $signed(add_ln700_16_fu_1911_p2);

assign sext_ln700_15_fu_1927_p1 = $signed(add_ln700_17_fu_1921_p2);

assign sext_ln700_16_fu_1937_p1 = $signed(add_ln700_18_fu_1931_p2);

assign sext_ln700_17_fu_1947_p1 = $signed(add_ln700_19_fu_1941_p2);

assign sext_ln700_18_fu_1957_p1 = $signed(add_ln700_20_fu_1951_p2);

assign sext_ln700_19_fu_1967_p1 = $signed(add_ln700_21_fu_1961_p2);

assign sext_ln700_1_fu_1769_p1 = $signed(add_ln700_fu_1763_p2);

assign sext_ln700_20_fu_1977_p1 = $signed(add_ln700_22_fu_1971_p2);

assign sext_ln700_21_fu_1987_p1 = $signed(add_ln700_23_fu_1981_p2);

assign sext_ln700_22_fu_1997_p1 = $signed(add_ln700_24_fu_1991_p2);

assign sext_ln700_23_fu_2007_p1 = $signed(add_ln700_25_fu_2001_p2);

assign sext_ln700_24_fu_2017_p1 = $signed(add_ln700_26_fu_2011_p2);

assign sext_ln700_25_fu_2027_p1 = $signed(add_ln700_27_fu_2021_p2);

assign sext_ln700_26_fu_2037_p1 = $signed(add_ln700_28_fu_2031_p2);

assign sext_ln700_2_fu_1785_p1 = $signed(add_ln700_2_fu_1779_p2);

assign sext_ln700_3_fu_1795_p1 = $signed(add_ln700_3_fu_1789_p2);

assign sext_ln700_4_fu_1805_p1 = $signed(add_ln700_4_fu_1799_p2);

assign sext_ln700_5_fu_1821_p1 = $signed(add_ln700_6_fu_1815_p2);

assign sext_ln700_6_fu_1831_p1 = $signed(add_ln700_7_fu_1825_p2);

assign sext_ln700_7_fu_1841_p1 = $signed(add_ln700_8_fu_1835_p2);

assign sext_ln700_8_fu_1851_p1 = $signed(add_ln700_9_fu_1845_p2);

assign sext_ln700_9_fu_1861_p1 = $signed(add_ln700_10_fu_1855_p2);

assign sext_ln700_fu_1759_p1 = mul_ln1352_29_fu_1753_p2;

assign sf_fu_555_p2 = (32'd1 + sf_1_fu_198);

assign threshs_m_thresholds_1_address0 = zext_ln186_fu_580_p1;

assign threshs_m_thresholds_2_address0 = zext_ln186_fu_580_p1;

assign threshs_m_thresholds_address0 = zext_ln186_fu_580_p1;

assign tile_1_fu_607_p3 = ((icmp_ln173_fu_593_p2[0:0] === 1'b1) ? 32'd0 : tile_fu_549_p2);

assign tile_fu_549_p2 = (32'd1 + tile_assign_fu_194);

assign tmp_V_2_fu_385_p1 = in_V_V_TDATA[59:0];

assign tmp_V_fu_2116_p2 = (add_ln700_30_fu_2110_p2 + zext_ln700_fu_2066_p1);

assign trunc_ln321_fu_389_p1 = sf_1_fu_198[2:0];

assign trunc_ln647_fu_929_p1 = ap_phi_reg_pp0_iter1_act_m_val_V_reg_302[1:0];

assign weights_m_weights_V_address0 = zext_ln137_fu_544_p1;

assign wgt_M_instance_0_V_fu_635_p1 = weights_m_weights_V_q0[1:0];

assign wgt_M_instance_10_s_fu_729_p4 = {{weights_m_weights_V_q0[21:20]}};

assign wgt_M_instance_11_s_fu_739_p4 = {{weights_m_weights_V_q0[23:22]}};

assign wgt_M_instance_12_s_fu_749_p4 = {{weights_m_weights_V_q0[25:24]}};

assign wgt_M_instance_13_s_fu_759_p4 = {{weights_m_weights_V_q0[27:26]}};

assign wgt_M_instance_14_s_fu_769_p4 = {{weights_m_weights_V_q0[29:28]}};

assign wgt_M_instance_15_s_fu_779_p4 = {{weights_m_weights_V_q0[31:30]}};

assign wgt_M_instance_16_s_fu_789_p4 = {{weights_m_weights_V_q0[33:32]}};

assign wgt_M_instance_17_s_fu_799_p4 = {{weights_m_weights_V_q0[35:34]}};

assign wgt_M_instance_18_s_fu_809_p4 = {{weights_m_weights_V_q0[37:36]}};

assign wgt_M_instance_19_s_fu_819_p4 = {{weights_m_weights_V_q0[39:38]}};

assign wgt_M_instance_1_V_fu_639_p4 = {{weights_m_weights_V_q0[3:2]}};

assign wgt_M_instance_20_s_fu_829_p4 = {{weights_m_weights_V_q0[41:40]}};

assign wgt_M_instance_21_s_fu_839_p4 = {{weights_m_weights_V_q0[43:42]}};

assign wgt_M_instance_22_s_fu_849_p4 = {{weights_m_weights_V_q0[45:44]}};

assign wgt_M_instance_23_s_fu_859_p4 = {{weights_m_weights_V_q0[47:46]}};

assign wgt_M_instance_24_s_fu_869_p4 = {{weights_m_weights_V_q0[49:48]}};

assign wgt_M_instance_25_s_fu_879_p4 = {{weights_m_weights_V_q0[51:50]}};

assign wgt_M_instance_26_s_fu_889_p4 = {{weights_m_weights_V_q0[53:52]}};

assign wgt_M_instance_27_s_fu_899_p4 = {{weights_m_weights_V_q0[55:54]}};

assign wgt_M_instance_28_s_fu_909_p4 = {{weights_m_weights_V_q0[57:56]}};

assign wgt_M_instance_29_s_fu_919_p4 = {{weights_m_weights_V_q0[59:58]}};

assign wgt_M_instance_2_V_fu_649_p4 = {{weights_m_weights_V_q0[5:4]}};

assign wgt_M_instance_3_V_fu_659_p4 = {{weights_m_weights_V_q0[7:6]}};

assign wgt_M_instance_4_V_fu_669_p4 = {{weights_m_weights_V_q0[9:8]}};

assign wgt_M_instance_5_V_fu_679_p4 = {{weights_m_weights_V_q0[11:10]}};

assign wgt_M_instance_6_V_fu_689_p4 = {{weights_m_weights_V_q0[13:12]}};

assign wgt_M_instance_7_V_fu_699_p4 = {{weights_m_weights_V_q0[15:14]}};

assign wgt_M_instance_8_V_fu_709_p4 = {{weights_m_weights_V_q0[17:16]}};

assign wgt_M_instance_9_V_fu_719_p4 = {{weights_m_weights_V_q0[19:18]}};

assign xor_ln899_1_fu_2082_p2 = (icmp_ln899_1_fu_2077_p2 ^ 1'd1);

assign xor_ln899_2_fu_2100_p2 = (icmp_ln899_2_fu_2095_p2 ^ 1'd1);

assign xor_ln899_fu_2060_p2 = (icmp_ln899_fu_2055_p2 ^ 1'd1);

assign zext_ln137_fu_544_p1 = tile_assign_fu_194;

assign zext_ln186_1_fu_2052_p1 = threshs_m_thresholds_4_reg_2246;

assign zext_ln186_2_fu_2073_p1 = $unsigned(sext_ln186_fu_2070_p1);

assign zext_ln186_3_fu_2092_p1 = threshs_m_thresholds_8_reg_2256;

assign zext_ln186_fu_580_p1 = nf_assign_fu_202;

assign zext_ln700_1_fu_2088_p1 = xor_ln899_1_fu_2082_p2;

assign zext_ln700_2_fu_2106_p1 = xor_ln899_2_fu_2100_p2;

assign zext_ln700_fu_2066_p1 = xor_ln899_fu_2060_p2;

endmodule //StreamingFCLayer_Batch_3_Matrix_Vector_Activa
