// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingFCLayer_Batch_3_Matrix_Vector_Activa (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY,
        weights_m_weights_V_address0,
        weights_m_weights_V_ce0,
        weights_m_weights_V_q0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [7:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;
output  [7:0] weights_m_weights_V_address0;
output   weights_m_weights_V_ce0;
input  [59:0] weights_m_weights_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg out_V_V_TVALID;
reg weights_m_weights_V_ce0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] threshs_m_thresholds_2_address0;
reg    threshs_m_thresholds_2_ce0;
wire   [2:0] threshs_m_thresholds_2_q0;
wire   [5:0] threshs_m_thresholds_1_address0;
reg    threshs_m_thresholds_1_ce0;
wire   [2:0] threshs_m_thresholds_1_q0;
wire   [5:0] threshs_m_thresholds_address0;
reg    threshs_m_thresholds_ce0;
wire   [4:0] threshs_m_thresholds_q0;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln122_fu_320_p2;
wire   [0:0] icmp_ln125_fu_335_p2;
reg    out_V_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln160_reg_2164;
reg   [0:0] icmp_ln160_reg_2164_pp0_iter1_reg;
reg   [7:0] i_0_reg_285;
reg    ap_predicate_op38_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_state4_io;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] i_fu_326_p2;
wire   [59:0] inElem_V_7_fu_360_p6;
wire   [59:0] tmp_V_2_fu_374_p1;
wire   [0:0] icmp_ln137_fu_488_p2;
reg   [0:0] icmp_ln137_reg_2154;
wire   [0:0] icmp_ln160_fu_511_p2;
wire   [9:0] add_ln700_29_fu_1991_p2;
reg   [9:0] add_ln700_29_reg_2183;
reg   [2:0] threshs_m_thresholds_4_reg_2190;
reg   [2:0] threshs_m_thresholds_6_reg_2195;
reg   [4:0] threshs_m_thresholds_8_reg_2200;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire   [59:0] ap_phi_reg_pp0_iter0_act_m_val_V_reg_296;
reg   [59:0] ap_phi_reg_pp0_iter1_act_m_val_V_reg_296;
wire   [63:0] zext_ln137_fu_494_p1;
wire   [63:0] zext_ln186_fu_530_p1;
reg   [9:0] accu_V_0_0_0_fu_188;
reg   [31:0] tile_assign_fu_192;
wire   [31:0] tile_fu_499_p2;
wire   [31:0] tile_1_fu_557_p3;
reg   [31:0] sf_1_fu_196;
wire   [31:0] sf_fu_505_p2;
reg   [31:0] nf_assign_fu_200;
wire   [31:0] nf_1_fu_549_p3;
reg   [59:0] inElem_V_1_fu_204;
wire   [59:0] inElem_V_10_fu_454_p3;
reg   [59:0] inElem_V_2_fu_208;
wire   [59:0] inElem_V_9_fu_446_p3;
reg   [59:0] inElem_V_3_fu_212;
wire   [59:0] inElem_V_6_fu_430_p3;
reg   [59:0] inElem_V_4_fu_216;
wire   [59:0] inElem_V_fu_414_p3;
reg    ap_block_pp0_stage0_01001;
wire   [1:0] inElem_V_7_fu_360_p5;
wire   [1:0] trunc_ln321_fu_378_p1;
wire   [0:0] icmp_ln321_2_fu_394_p2;
wire   [0:0] icmp_ln321_1_fu_388_p2;
wire   [0:0] icmp_ln321_fu_382_p2;
wire   [0:0] or_ln321_fu_400_p2;
wire   [59:0] select_ln321_fu_406_p3;
wire   [59:0] select_ln321_2_fu_422_p3;
wire   [59:0] inElem_V_8_fu_438_p3;
wire   [31:0] nf_fu_537_p2;
wire   [0:0] icmp_ln173_fu_543_p2;
wire  signed [1:0] wgt_M_instance_0_V_fu_585_p1;
wire   [1:0] trunc_ln647_fu_879_p1;
wire   [1:0] mul_ln1352_fu_891_p0;
wire  signed [3:0] mul_ln1352_fu_891_p2;
wire  signed [1:0] wgt_M_instance_1_V_fu_589_p4;
wire   [1:0] arg_V_read_assign_1_fu_901_p4;
wire   [1:0] mul_ln1352_1_fu_919_p0;
wire  signed [3:0] mul_ln1352_1_fu_919_p2;
wire  signed [1:0] wgt_M_instance_2_V_fu_599_p4;
wire   [1:0] arg_V_read_assign_2_fu_929_p4;
wire   [1:0] mul_ln1352_2_fu_947_p0;
wire  signed [3:0] mul_ln1352_2_fu_947_p2;
wire  signed [1:0] wgt_M_instance_3_V_fu_609_p4;
wire   [1:0] arg_V_read_assign_3_fu_957_p4;
wire   [1:0] mul_ln1352_3_fu_975_p0;
wire  signed [3:0] mul_ln1352_3_fu_975_p2;
wire  signed [1:0] wgt_M_instance_4_V_fu_619_p4;
wire   [1:0] arg_V_read_assign_4_fu_985_p4;
wire   [1:0] mul_ln1352_4_fu_1003_p0;
wire  signed [3:0] mul_ln1352_4_fu_1003_p2;
wire  signed [1:0] wgt_M_instance_5_V_fu_629_p4;
wire   [1:0] arg_V_read_assign_5_fu_1013_p4;
wire   [1:0] mul_ln1352_5_fu_1031_p0;
wire  signed [3:0] mul_ln1352_5_fu_1031_p2;
wire  signed [1:0] wgt_M_instance_6_V_fu_639_p4;
wire   [1:0] arg_V_read_assign_6_fu_1041_p4;
wire   [1:0] mul_ln1352_6_fu_1059_p0;
wire  signed [3:0] mul_ln1352_6_fu_1059_p2;
wire  signed [1:0] wgt_M_instance_7_V_fu_649_p4;
wire   [1:0] arg_V_read_assign_7_fu_1069_p4;
wire   [1:0] mul_ln1352_7_fu_1087_p0;
wire  signed [3:0] mul_ln1352_7_fu_1087_p2;
wire  signed [1:0] wgt_M_instance_8_V_fu_659_p4;
wire   [1:0] arg_V_read_assign_8_fu_1097_p4;
wire   [1:0] mul_ln1352_8_fu_1115_p0;
wire  signed [3:0] mul_ln1352_8_fu_1115_p2;
wire  signed [1:0] wgt_M_instance_9_V_fu_669_p4;
wire   [1:0] arg_V_read_assign_9_fu_1125_p4;
wire   [1:0] mul_ln1352_9_fu_1143_p0;
wire  signed [3:0] mul_ln1352_9_fu_1143_p2;
wire  signed [1:0] wgt_M_instance_10_s_fu_679_p4;
wire   [1:0] arg_V_read_assign_s_fu_1153_p4;
wire   [1:0] mul_ln1352_10_fu_1171_p0;
wire  signed [3:0] mul_ln1352_10_fu_1171_p2;
wire  signed [1:0] wgt_M_instance_11_s_fu_689_p4;
wire   [1:0] arg_V_read_assign_10_fu_1181_p4;
wire   [1:0] mul_ln1352_11_fu_1199_p0;
wire  signed [3:0] mul_ln1352_11_fu_1199_p2;
wire  signed [1:0] wgt_M_instance_12_s_fu_699_p4;
wire   [1:0] arg_V_read_assign_11_fu_1209_p4;
wire   [1:0] mul_ln1352_12_fu_1227_p0;
wire  signed [3:0] mul_ln1352_12_fu_1227_p2;
wire  signed [1:0] wgt_M_instance_13_s_fu_709_p4;
wire   [1:0] arg_V_read_assign_12_fu_1237_p4;
wire   [1:0] mul_ln1352_13_fu_1255_p0;
wire  signed [3:0] mul_ln1352_13_fu_1255_p2;
wire  signed [1:0] wgt_M_instance_14_s_fu_719_p4;
wire   [1:0] arg_V_read_assign_13_fu_1265_p4;
wire   [1:0] mul_ln1352_14_fu_1283_p0;
wire  signed [3:0] mul_ln1352_14_fu_1283_p2;
wire  signed [1:0] wgt_M_instance_15_s_fu_729_p4;
wire   [1:0] arg_V_read_assign_14_fu_1293_p4;
wire   [1:0] mul_ln1352_15_fu_1311_p0;
wire  signed [3:0] mul_ln1352_15_fu_1311_p2;
wire  signed [1:0] wgt_M_instance_16_s_fu_739_p4;
wire   [1:0] arg_V_read_assign_15_fu_1321_p4;
wire   [1:0] mul_ln1352_16_fu_1339_p0;
wire  signed [3:0] mul_ln1352_16_fu_1339_p2;
wire  signed [1:0] wgt_M_instance_17_s_fu_749_p4;
wire   [1:0] arg_V_read_assign_16_fu_1349_p4;
wire   [1:0] mul_ln1352_17_fu_1367_p0;
wire  signed [3:0] mul_ln1352_17_fu_1367_p2;
wire  signed [1:0] wgt_M_instance_18_s_fu_759_p4;
wire   [1:0] arg_V_read_assign_17_fu_1377_p4;
wire   [1:0] mul_ln1352_18_fu_1395_p0;
wire  signed [3:0] mul_ln1352_18_fu_1395_p2;
wire  signed [1:0] wgt_M_instance_19_s_fu_769_p4;
wire   [1:0] arg_V_read_assign_18_fu_1405_p4;
wire   [1:0] mul_ln1352_19_fu_1423_p0;
wire  signed [3:0] mul_ln1352_19_fu_1423_p2;
wire  signed [1:0] wgt_M_instance_20_s_fu_779_p4;
wire   [1:0] arg_V_read_assign_19_fu_1433_p4;
wire   [1:0] mul_ln1352_20_fu_1451_p0;
wire  signed [3:0] mul_ln1352_20_fu_1451_p2;
wire  signed [1:0] wgt_M_instance_21_s_fu_789_p4;
wire   [1:0] arg_V_read_assign_20_fu_1461_p4;
wire   [1:0] mul_ln1352_21_fu_1479_p0;
wire  signed [3:0] mul_ln1352_21_fu_1479_p2;
wire  signed [1:0] wgt_M_instance_22_s_fu_799_p4;
wire   [1:0] arg_V_read_assign_21_fu_1489_p4;
wire   [1:0] mul_ln1352_22_fu_1507_p0;
wire  signed [3:0] mul_ln1352_22_fu_1507_p2;
wire  signed [1:0] wgt_M_instance_23_s_fu_809_p4;
wire   [1:0] arg_V_read_assign_22_fu_1517_p4;
wire   [1:0] mul_ln1352_23_fu_1535_p0;
wire  signed [3:0] mul_ln1352_23_fu_1535_p2;
wire  signed [1:0] wgt_M_instance_24_s_fu_819_p4;
wire   [1:0] arg_V_read_assign_23_fu_1545_p4;
wire   [1:0] mul_ln1352_24_fu_1563_p0;
wire  signed [3:0] mul_ln1352_24_fu_1563_p2;
wire  signed [1:0] wgt_M_instance_25_s_fu_829_p4;
wire   [1:0] arg_V_read_assign_24_fu_1573_p4;
wire   [1:0] mul_ln1352_25_fu_1591_p0;
wire  signed [3:0] mul_ln1352_25_fu_1591_p2;
wire  signed [1:0] wgt_M_instance_26_s_fu_839_p4;
wire   [1:0] arg_V_read_assign_25_fu_1601_p4;
wire   [1:0] mul_ln1352_26_fu_1619_p0;
wire  signed [3:0] mul_ln1352_26_fu_1619_p2;
wire  signed [1:0] wgt_M_instance_27_s_fu_849_p4;
wire   [1:0] arg_V_read_assign_26_fu_1629_p4;
wire   [1:0] mul_ln1352_27_fu_1647_p0;
wire  signed [3:0] mul_ln1352_27_fu_1647_p2;
wire  signed [1:0] wgt_M_instance_28_s_fu_859_p4;
wire   [1:0] arg_V_read_assign_27_fu_1657_p4;
wire   [1:0] mul_ln1352_28_fu_1675_p0;
wire  signed [3:0] mul_ln1352_28_fu_1675_p2;
wire  signed [1:0] wgt_M_instance_29_s_fu_869_p4;
wire   [1:0] arg_V_read_assign_28_fu_1685_p4;
wire   [1:0] mul_ln1352_29_fu_1703_p0;
wire  signed [3:0] mul_ln1352_29_fu_1703_p2;
wire  signed [4:0] sext_ln170_28_fu_1681_p1;
wire  signed [4:0] sext_ln170_27_fu_1653_p1;
wire   [4:0] add_ln700_fu_1713_p2;
wire   [9:0] res_V_fu_578_p3;
wire  signed [9:0] sext_ln700_1_fu_1719_p1;
wire  signed [4:0] sext_ln170_25_fu_1597_p1;
wire  signed [4:0] sext_ln170_26_fu_1625_p1;
wire   [4:0] add_ln700_2_fu_1729_p2;
wire  signed [4:0] sext_ln170_21_fu_1485_p1;
wire  signed [4:0] sext_ln170_22_fu_1513_p1;
wire   [4:0] add_ln700_3_fu_1739_p2;
wire  signed [5:0] sext_ln700_2_fu_1735_p1;
wire  signed [5:0] sext_ln700_3_fu_1745_p1;
wire   [5:0] add_ln700_4_fu_1749_p2;
wire   [9:0] add_ln700_1_fu_1723_p2;
wire  signed [9:0] sext_ln700_4_fu_1755_p1;
wire  signed [4:0] sext_ln170_23_fu_1541_p1;
wire  signed [4:0] sext_ln170_24_fu_1569_p1;
wire   [4:0] add_ln700_6_fu_1765_p2;
wire  signed [4:0] sext_ln170_16_fu_1345_p1;
wire  signed [4:0] sext_ln170_14_fu_1289_p1;
wire   [4:0] add_ln700_7_fu_1775_p2;
wire  signed [5:0] sext_ln700_5_fu_1771_p1;
wire  signed [5:0] sext_ln700_6_fu_1781_p1;
wire   [5:0] add_ln700_8_fu_1785_p2;
wire  signed [4:0] sext_ln170_18_fu_1401_p1;
wire  signed [4:0] sext_ln170_15_fu_1317_p1;
wire   [4:0] add_ln700_9_fu_1795_p2;
wire  signed [4:0] sext_ln170_20_fu_1457_p1;
wire  signed [4:0] sext_ln170_17_fu_1373_p1;
wire   [4:0] add_ln700_10_fu_1805_p2;
wire  signed [5:0] sext_ln700_8_fu_1801_p1;
wire  signed [5:0] sext_ln700_9_fu_1811_p1;
wire   [5:0] add_ln700_11_fu_1815_p2;
wire  signed [6:0] sext_ln700_7_fu_1791_p1;
wire  signed [6:0] sext_ln700_10_fu_1821_p1;
wire   [6:0] add_ln700_12_fu_1825_p2;
wire   [9:0] add_ln700_5_fu_1759_p2;
wire  signed [9:0] sext_ln700_11_fu_1831_p1;
wire  signed [4:0] sext_ln170_1_fu_925_p1;
wire  signed [4:0] sext_ln170_19_fu_1429_p1;
wire   [4:0] add_ln700_14_fu_1841_p2;
wire  signed [4:0] sext_ln170_3_fu_981_p1;
wire  signed [4:0] sext_ln170_fu_897_p1;
wire   [4:0] add_ln700_15_fu_1851_p2;
wire  signed [5:0] sext_ln700_12_fu_1847_p1;
wire  signed [5:0] sext_ln700_13_fu_1857_p1;
wire   [5:0] add_ln700_16_fu_1861_p2;
wire  signed [4:0] sext_ln170_5_fu_1037_p1;
wire  signed [4:0] sext_ln170_2_fu_953_p1;
wire   [4:0] add_ln700_17_fu_1871_p2;
wire  signed [4:0] sext_ln170_7_fu_1093_p1;
wire  signed [4:0] sext_ln170_4_fu_1009_p1;
wire   [4:0] add_ln700_18_fu_1881_p2;
wire  signed [5:0] sext_ln700_15_fu_1877_p1;
wire  signed [5:0] sext_ln700_16_fu_1887_p1;
wire   [5:0] add_ln700_19_fu_1891_p2;
wire  signed [6:0] sext_ln700_14_fu_1867_p1;
wire  signed [6:0] sext_ln700_17_fu_1897_p1;
wire   [6:0] add_ln700_20_fu_1901_p2;
wire  signed [4:0] sext_ln170_9_fu_1149_p1;
wire  signed [4:0] sext_ln170_6_fu_1065_p1;
wire   [4:0] add_ln700_21_fu_1911_p2;
wire  signed [4:0] sext_ln170_11_fu_1205_p1;
wire  signed [4:0] sext_ln170_8_fu_1121_p1;
wire   [4:0] add_ln700_22_fu_1921_p2;
wire  signed [5:0] sext_ln700_19_fu_1917_p1;
wire  signed [5:0] sext_ln700_20_fu_1927_p1;
wire   [5:0] add_ln700_23_fu_1931_p2;
wire  signed [4:0] sext_ln170_13_fu_1261_p1;
wire  signed [4:0] sext_ln170_10_fu_1177_p1;
wire   [4:0] add_ln700_24_fu_1941_p2;
wire  signed [4:0] sext_ln700_fu_1709_p1;
wire  signed [4:0] sext_ln170_12_fu_1233_p1;
wire   [4:0] add_ln700_25_fu_1951_p2;
wire  signed [5:0] sext_ln700_22_fu_1947_p1;
wire  signed [5:0] sext_ln700_23_fu_1957_p1;
wire   [5:0] add_ln700_26_fu_1961_p2;
wire  signed [6:0] sext_ln700_21_fu_1937_p1;
wire  signed [6:0] sext_ln700_24_fu_1967_p1;
wire   [6:0] add_ln700_27_fu_1971_p2;
wire  signed [7:0] sext_ln700_18_fu_1907_p1;
wire  signed [7:0] sext_ln700_25_fu_1977_p1;
wire   [7:0] add_ln700_28_fu_1981_p2;
wire   [9:0] add_ln700_13_fu_1835_p2;
wire  signed [9:0] sext_ln700_26_fu_1987_p1;
wire   [9:0] zext_ln186_1_fu_2002_p1;
wire   [0:0] icmp_ln899_fu_2005_p2;
wire   [0:0] xor_ln899_fu_2010_p2;
wire  signed [3:0] sext_ln186_fu_2020_p1;
wire   [9:0] zext_ln186_2_fu_2023_p1;
wire   [0:0] icmp_ln899_1_fu_2027_p2;
wire   [0:0] xor_ln899_1_fu_2032_p2;
wire   [9:0] zext_ln186_3_fu_2042_p1;
wire   [0:0] icmp_ln899_2_fu_2045_p2;
wire   [0:0] xor_ln899_2_fu_2050_p2;
wire   [1:0] zext_ln700_1_fu_2038_p1;
wire   [1:0] zext_ln700_2_fu_2056_p1;
wire   [1:0] add_ln700_30_fu_2060_p2;
wire   [1:0] zext_ln700_fu_2016_p1;
wire   [1:0] tmp_V_fu_2066_p2;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [3:0] mul_ln1352_10_fu_1171_p00;
wire   [3:0] mul_ln1352_11_fu_1199_p00;
wire   [3:0] mul_ln1352_12_fu_1227_p00;
wire   [3:0] mul_ln1352_13_fu_1255_p00;
wire   [3:0] mul_ln1352_14_fu_1283_p00;
wire   [3:0] mul_ln1352_15_fu_1311_p00;
wire   [3:0] mul_ln1352_16_fu_1339_p00;
wire   [3:0] mul_ln1352_17_fu_1367_p00;
wire   [3:0] mul_ln1352_18_fu_1395_p00;
wire   [3:0] mul_ln1352_19_fu_1423_p00;
wire   [3:0] mul_ln1352_1_fu_919_p00;
wire   [3:0] mul_ln1352_20_fu_1451_p00;
wire   [3:0] mul_ln1352_21_fu_1479_p00;
wire   [3:0] mul_ln1352_22_fu_1507_p00;
wire   [3:0] mul_ln1352_23_fu_1535_p00;
wire   [3:0] mul_ln1352_24_fu_1563_p00;
wire   [3:0] mul_ln1352_25_fu_1591_p00;
wire   [3:0] mul_ln1352_26_fu_1619_p00;
wire   [3:0] mul_ln1352_27_fu_1647_p00;
wire   [3:0] mul_ln1352_28_fu_1675_p00;
wire   [3:0] mul_ln1352_29_fu_1703_p00;
wire   [3:0] mul_ln1352_2_fu_947_p00;
wire   [3:0] mul_ln1352_3_fu_975_p00;
wire   [3:0] mul_ln1352_4_fu_1003_p00;
wire   [3:0] mul_ln1352_5_fu_1031_p00;
wire   [3:0] mul_ln1352_6_fu_1059_p00;
wire   [3:0] mul_ln1352_7_fu_1087_p00;
wire   [3:0] mul_ln1352_8_fu_1115_p00;
wire   [3:0] mul_ln1352_9_fu_1143_p00;
wire   [3:0] mul_ln1352_fu_891_p00;
reg    ap_condition_112;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

StreamingFCLayer_Batch_3_Matrix_Vector_Actbkb #(
    .DataWidth( 3 ),
    .AddressRange( 60 ),
    .AddressWidth( 6 ))
threshs_m_thresholds_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_2_address0),
    .ce0(threshs_m_thresholds_2_ce0),
    .q0(threshs_m_thresholds_2_q0)
);

StreamingFCLayer_Batch_3_Matrix_Vector_Actbkb #(
    .DataWidth( 3 ),
    .AddressRange( 60 ),
    .AddressWidth( 6 ))
threshs_m_thresholds_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_1_address0),
    .ce0(threshs_m_thresholds_1_ce0),
    .q0(threshs_m_thresholds_1_q0)
);

StreamingFCLayer_Batch_3_Matrix_Vector_ActdEe #(
    .DataWidth( 5 ),
    .AddressRange( 60 ),
    .AddressWidth( 6 ))
threshs_m_thresholds_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_address0),
    .ce0(threshs_m_thresholds_ce0),
    .q0(threshs_m_thresholds_q0)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 60 ),
    .din1_WIDTH( 60 ),
    .din2_WIDTH( 60 ),
    .din3_WIDTH( 60 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 60 ))
StreamingFCLayer_eOg_U1(
    .din0(inElem_V_1_fu_204),
    .din1(inElem_V_2_fu_208),
    .din2(inElem_V_3_fu_212),
    .din3(inElem_V_4_fu_216),
    .din4(inElem_V_7_fu_360_p5),
    .dout(inElem_V_7_fu_360_p6)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U2(
    .din0(mul_ln1352_fu_891_p0),
    .din1(wgt_M_instance_0_V_fu_585_p1),
    .dout(mul_ln1352_fu_891_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U3(
    .din0(mul_ln1352_1_fu_919_p0),
    .din1(wgt_M_instance_1_V_fu_589_p4),
    .dout(mul_ln1352_1_fu_919_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U4(
    .din0(mul_ln1352_2_fu_947_p0),
    .din1(wgt_M_instance_2_V_fu_599_p4),
    .dout(mul_ln1352_2_fu_947_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U5(
    .din0(mul_ln1352_3_fu_975_p0),
    .din1(wgt_M_instance_3_V_fu_609_p4),
    .dout(mul_ln1352_3_fu_975_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U6(
    .din0(mul_ln1352_4_fu_1003_p0),
    .din1(wgt_M_instance_4_V_fu_619_p4),
    .dout(mul_ln1352_4_fu_1003_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U7(
    .din0(mul_ln1352_5_fu_1031_p0),
    .din1(wgt_M_instance_5_V_fu_629_p4),
    .dout(mul_ln1352_5_fu_1031_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U8(
    .din0(mul_ln1352_6_fu_1059_p0),
    .din1(wgt_M_instance_6_V_fu_639_p4),
    .dout(mul_ln1352_6_fu_1059_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U9(
    .din0(mul_ln1352_7_fu_1087_p0),
    .din1(wgt_M_instance_7_V_fu_649_p4),
    .dout(mul_ln1352_7_fu_1087_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U10(
    .din0(mul_ln1352_8_fu_1115_p0),
    .din1(wgt_M_instance_8_V_fu_659_p4),
    .dout(mul_ln1352_8_fu_1115_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U11(
    .din0(mul_ln1352_9_fu_1143_p0),
    .din1(wgt_M_instance_9_V_fu_669_p4),
    .dout(mul_ln1352_9_fu_1143_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U12(
    .din0(mul_ln1352_10_fu_1171_p0),
    .din1(wgt_M_instance_10_s_fu_679_p4),
    .dout(mul_ln1352_10_fu_1171_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U13(
    .din0(mul_ln1352_11_fu_1199_p0),
    .din1(wgt_M_instance_11_s_fu_689_p4),
    .dout(mul_ln1352_11_fu_1199_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U14(
    .din0(mul_ln1352_12_fu_1227_p0),
    .din1(wgt_M_instance_12_s_fu_699_p4),
    .dout(mul_ln1352_12_fu_1227_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U15(
    .din0(mul_ln1352_13_fu_1255_p0),
    .din1(wgt_M_instance_13_s_fu_709_p4),
    .dout(mul_ln1352_13_fu_1255_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U16(
    .din0(mul_ln1352_14_fu_1283_p0),
    .din1(wgt_M_instance_14_s_fu_719_p4),
    .dout(mul_ln1352_14_fu_1283_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U17(
    .din0(mul_ln1352_15_fu_1311_p0),
    .din1(wgt_M_instance_15_s_fu_729_p4),
    .dout(mul_ln1352_15_fu_1311_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U18(
    .din0(mul_ln1352_16_fu_1339_p0),
    .din1(wgt_M_instance_16_s_fu_739_p4),
    .dout(mul_ln1352_16_fu_1339_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U19(
    .din0(mul_ln1352_17_fu_1367_p0),
    .din1(wgt_M_instance_17_s_fu_749_p4),
    .dout(mul_ln1352_17_fu_1367_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U20(
    .din0(mul_ln1352_18_fu_1395_p0),
    .din1(wgt_M_instance_18_s_fu_759_p4),
    .dout(mul_ln1352_18_fu_1395_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U21(
    .din0(mul_ln1352_19_fu_1423_p0),
    .din1(wgt_M_instance_19_s_fu_769_p4),
    .dout(mul_ln1352_19_fu_1423_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U22(
    .din0(mul_ln1352_20_fu_1451_p0),
    .din1(wgt_M_instance_20_s_fu_779_p4),
    .dout(mul_ln1352_20_fu_1451_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U23(
    .din0(mul_ln1352_21_fu_1479_p0),
    .din1(wgt_M_instance_21_s_fu_789_p4),
    .dout(mul_ln1352_21_fu_1479_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U24(
    .din0(mul_ln1352_22_fu_1507_p0),
    .din1(wgt_M_instance_22_s_fu_799_p4),
    .dout(mul_ln1352_22_fu_1507_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U25(
    .din0(mul_ln1352_23_fu_1535_p0),
    .din1(wgt_M_instance_23_s_fu_809_p4),
    .dout(mul_ln1352_23_fu_1535_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U26(
    .din0(mul_ln1352_24_fu_1563_p0),
    .din1(wgt_M_instance_24_s_fu_819_p4),
    .dout(mul_ln1352_24_fu_1563_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U27(
    .din0(mul_ln1352_25_fu_1591_p0),
    .din1(wgt_M_instance_25_s_fu_829_p4),
    .dout(mul_ln1352_25_fu_1591_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U28(
    .din0(mul_ln1352_26_fu_1619_p0),
    .din1(wgt_M_instance_26_s_fu_839_p4),
    .dout(mul_ln1352_26_fu_1619_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U29(
    .din0(mul_ln1352_27_fu_1647_p0),
    .din1(wgt_M_instance_27_s_fu_849_p4),
    .dout(mul_ln1352_27_fu_1647_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U30(
    .din0(mul_ln1352_28_fu_1675_p0),
    .din1(wgt_M_instance_28_s_fu_859_p4),
    .dout(mul_ln1352_28_fu_1675_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_fYi_U31(
    .din0(mul_ln1352_29_fu_1703_p0),
    .din1(wgt_M_instance_29_s_fu_869_p4),
    .dout(mul_ln1352_29_fu_1703_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_112)) begin
        if (((icmp_ln125_fu_335_p2 == 1'd0) & (icmp_ln122_fu_320_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_act_m_val_V_reg_296 <= inElem_V_7_fu_360_p6;
        end else if (((icmp_ln125_fu_335_p2 == 1'd1) & (icmp_ln122_fu_320_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_act_m_val_V_reg_296 <= tmp_V_2_fu_374_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_act_m_val_V_reg_296 <= ap_phi_reg_pp0_iter0_act_m_val_V_reg_296;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln122_fu_320_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_0_reg_285 <= i_fu_326_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_285 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln160_fu_511_p2 == 1'd1) & (icmp_ln122_fu_320_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nf_assign_fu_200 <= nf_1_fu_549_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nf_assign_fu_200 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln160_fu_511_p2 == 1'd0) & (icmp_ln122_fu_320_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sf_1_fu_196 <= sf_fu_505_p2;
    end else if ((((icmp_ln160_fu_511_p2 == 1'd1) & (icmp_ln122_fu_320_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sf_1_fu_196 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln160_fu_511_p2 == 1'd1) & (icmp_ln122_fu_320_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tile_assign_fu_192 <= tile_1_fu_557_p3;
    end else if (((icmp_ln160_fu_511_p2 == 1'd0) & (icmp_ln122_fu_320_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tile_assign_fu_192 <= tile_fu_499_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_assign_fu_192 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        accu_V_0_0_0_fu_188 <= add_ln700_29_fu_1991_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln700_29_reg_2183 <= add_ln700_29_fu_1991_p2;
        icmp_ln160_reg_2164_pp0_iter1_reg <= icmp_ln160_reg_2164;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln122_fu_320_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln137_reg_2154 <= icmp_ln137_fu_488_p2;
        icmp_ln160_reg_2164 <= icmp_ln160_fu_511_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln125_fu_335_p2 == 1'd1) & (icmp_ln122_fu_320_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inElem_V_1_fu_204 <= inElem_V_10_fu_454_p3;
        inElem_V_2_fu_208 <= inElem_V_9_fu_446_p3;
        inElem_V_3_fu_212 <= inElem_V_6_fu_430_p3;
        inElem_V_4_fu_216 <= inElem_V_fu_414_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln160_reg_2164 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_4_reg_2190 <= threshs_m_thresholds_2_q0;
        threshs_m_thresholds_6_reg_2195 <= threshs_m_thresholds_1_q0;
        threshs_m_thresholds_8_reg_2200 <= threshs_m_thresholds_q0;
    end
end

always @ (*) begin
    if ((icmp_ln122_fu_320_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln125_fu_335_p2 == 1'd1) & (icmp_ln122_fu_320_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_V_V_TDATA_blk_n = in_V_V_TVALID;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op38_read_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_reg_2164_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_V_V_TDATA_blk_n = out_V_V_TREADY;
    end else begin
        out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln160_reg_2164_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_V_V_TVALID = 1'b1;
    end else begin
        out_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_1_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_2_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights_m_weights_V_ce0 = 1'b1;
    end else begin
        weights_m_weights_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln122_fu_320_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((icmp_ln122_fu_320_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln700_10_fu_1805_p2 = ($signed(sext_ln170_20_fu_1457_p1) + $signed(sext_ln170_17_fu_1373_p1));

assign add_ln700_11_fu_1815_p2 = ($signed(sext_ln700_8_fu_1801_p1) + $signed(sext_ln700_9_fu_1811_p1));

assign add_ln700_12_fu_1825_p2 = ($signed(sext_ln700_7_fu_1791_p1) + $signed(sext_ln700_10_fu_1821_p1));

assign add_ln700_13_fu_1835_p2 = ($signed(add_ln700_5_fu_1759_p2) + $signed(sext_ln700_11_fu_1831_p1));

assign add_ln700_14_fu_1841_p2 = ($signed(sext_ln170_1_fu_925_p1) + $signed(sext_ln170_19_fu_1429_p1));

assign add_ln700_15_fu_1851_p2 = ($signed(sext_ln170_3_fu_981_p1) + $signed(sext_ln170_fu_897_p1));

assign add_ln700_16_fu_1861_p2 = ($signed(sext_ln700_12_fu_1847_p1) + $signed(sext_ln700_13_fu_1857_p1));

assign add_ln700_17_fu_1871_p2 = ($signed(sext_ln170_5_fu_1037_p1) + $signed(sext_ln170_2_fu_953_p1));

assign add_ln700_18_fu_1881_p2 = ($signed(sext_ln170_7_fu_1093_p1) + $signed(sext_ln170_4_fu_1009_p1));

assign add_ln700_19_fu_1891_p2 = ($signed(sext_ln700_15_fu_1877_p1) + $signed(sext_ln700_16_fu_1887_p1));

assign add_ln700_1_fu_1723_p2 = ($signed(res_V_fu_578_p3) + $signed(sext_ln700_1_fu_1719_p1));

assign add_ln700_20_fu_1901_p2 = ($signed(sext_ln700_14_fu_1867_p1) + $signed(sext_ln700_17_fu_1897_p1));

assign add_ln700_21_fu_1911_p2 = ($signed(sext_ln170_9_fu_1149_p1) + $signed(sext_ln170_6_fu_1065_p1));

assign add_ln700_22_fu_1921_p2 = ($signed(sext_ln170_11_fu_1205_p1) + $signed(sext_ln170_8_fu_1121_p1));

assign add_ln700_23_fu_1931_p2 = ($signed(sext_ln700_19_fu_1917_p1) + $signed(sext_ln700_20_fu_1927_p1));

assign add_ln700_24_fu_1941_p2 = ($signed(sext_ln170_13_fu_1261_p1) + $signed(sext_ln170_10_fu_1177_p1));

assign add_ln700_25_fu_1951_p2 = ($signed(sext_ln700_fu_1709_p1) + $signed(sext_ln170_12_fu_1233_p1));

assign add_ln700_26_fu_1961_p2 = ($signed(sext_ln700_22_fu_1947_p1) + $signed(sext_ln700_23_fu_1957_p1));

assign add_ln700_27_fu_1971_p2 = ($signed(sext_ln700_21_fu_1937_p1) + $signed(sext_ln700_24_fu_1967_p1));

assign add_ln700_28_fu_1981_p2 = ($signed(sext_ln700_18_fu_1907_p1) + $signed(sext_ln700_25_fu_1977_p1));

assign add_ln700_29_fu_1991_p2 = ($signed(add_ln700_13_fu_1835_p2) + $signed(sext_ln700_26_fu_1987_p1));

assign add_ln700_2_fu_1729_p2 = ($signed(sext_ln170_25_fu_1597_p1) + $signed(sext_ln170_26_fu_1625_p1));

assign add_ln700_30_fu_2060_p2 = (zext_ln700_1_fu_2038_p1 + zext_ln700_2_fu_2056_p1);

assign add_ln700_3_fu_1739_p2 = ($signed(sext_ln170_21_fu_1485_p1) + $signed(sext_ln170_22_fu_1513_p1));

assign add_ln700_4_fu_1749_p2 = ($signed(sext_ln700_2_fu_1735_p1) + $signed(sext_ln700_3_fu_1745_p1));

assign add_ln700_5_fu_1759_p2 = ($signed(add_ln700_1_fu_1723_p2) + $signed(sext_ln700_4_fu_1755_p1));

assign add_ln700_6_fu_1765_p2 = ($signed(sext_ln170_23_fu_1541_p1) + $signed(sext_ln170_24_fu_1569_p1));

assign add_ln700_7_fu_1775_p2 = ($signed(sext_ln170_16_fu_1345_p1) + $signed(sext_ln170_14_fu_1289_p1));

assign add_ln700_8_fu_1785_p2 = ($signed(sext_ln700_5_fu_1771_p1) + $signed(sext_ln700_6_fu_1781_p1));

assign add_ln700_9_fu_1795_p2 = ($signed(sext_ln170_18_fu_1401_p1) + $signed(sext_ln170_15_fu_1317_p1));

assign add_ln700_fu_1713_p2 = ($signed(sext_ln170_28_fu_1681_p1) + $signed(sext_ln170_27_fu_1653_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((in_V_V_TVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op38_read_state2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((in_V_V_TVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op38_read_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((in_V_V_TVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op38_read_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((in_V_V_TVALID == 1'b0) & (ap_predicate_op38_read_state2 == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((icmp_ln160_reg_2164_pp0_iter1_reg == 1'd1) & (out_V_V_TREADY == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_112 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_act_m_val_V_reg_296 = 'bx;

always @ (*) begin
    ap_predicate_op38_read_state2 = ((icmp_ln125_fu_335_p2 == 1'd1) & (icmp_ln122_fu_320_p2 == 1'd0));
end

assign arg_V_read_assign_10_fu_1181_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[23:22]}};

assign arg_V_read_assign_11_fu_1209_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[25:24]}};

assign arg_V_read_assign_12_fu_1237_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[27:26]}};

assign arg_V_read_assign_13_fu_1265_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[29:28]}};

assign arg_V_read_assign_14_fu_1293_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[31:30]}};

assign arg_V_read_assign_15_fu_1321_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[33:32]}};

assign arg_V_read_assign_16_fu_1349_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[35:34]}};

assign arg_V_read_assign_17_fu_1377_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[37:36]}};

assign arg_V_read_assign_18_fu_1405_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[39:38]}};

assign arg_V_read_assign_19_fu_1433_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[41:40]}};

assign arg_V_read_assign_1_fu_901_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[3:2]}};

assign arg_V_read_assign_20_fu_1461_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[43:42]}};

assign arg_V_read_assign_21_fu_1489_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[45:44]}};

assign arg_V_read_assign_22_fu_1517_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[47:46]}};

assign arg_V_read_assign_23_fu_1545_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[49:48]}};

assign arg_V_read_assign_24_fu_1573_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[51:50]}};

assign arg_V_read_assign_25_fu_1601_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[53:52]}};

assign arg_V_read_assign_26_fu_1629_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[55:54]}};

assign arg_V_read_assign_27_fu_1657_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[57:56]}};

assign arg_V_read_assign_28_fu_1685_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[59:58]}};

assign arg_V_read_assign_2_fu_929_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[5:4]}};

assign arg_V_read_assign_3_fu_957_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[7:6]}};

assign arg_V_read_assign_4_fu_985_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[9:8]}};

assign arg_V_read_assign_5_fu_1013_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[11:10]}};

assign arg_V_read_assign_6_fu_1041_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[13:12]}};

assign arg_V_read_assign_7_fu_1069_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[15:14]}};

assign arg_V_read_assign_8_fu_1097_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[17:16]}};

assign arg_V_read_assign_9_fu_1125_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[19:18]}};

assign arg_V_read_assign_s_fu_1153_p4 = {{ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[21:20]}};

assign i_fu_326_p2 = (i_0_reg_285 + 8'd1);

assign icmp_ln122_fu_320_p2 = ((i_0_reg_285 == 8'd240) ? 1'b1 : 1'b0);

assign icmp_ln125_fu_335_p2 = ((nf_assign_fu_200 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln137_fu_488_p2 = ((sf_1_fu_196 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln160_fu_511_p2 = ((sf_fu_505_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln173_fu_543_p2 = ((nf_fu_537_p2 == 32'd60) ? 1'b1 : 1'b0);

assign icmp_ln321_1_fu_388_p2 = ((trunc_ln321_fu_378_p1 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln321_2_fu_394_p2 = ((trunc_ln321_fu_378_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln321_fu_382_p2 = ((trunc_ln321_fu_378_p1 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln899_1_fu_2027_p2 = (($signed(add_ln700_29_reg_2183) < $signed(zext_ln186_2_fu_2023_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_2_fu_2045_p2 = (($signed(add_ln700_29_reg_2183) < $signed(zext_ln186_3_fu_2042_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_fu_2005_p2 = (($signed(add_ln700_29_reg_2183) < $signed(zext_ln186_1_fu_2002_p1)) ? 1'b1 : 1'b0);

assign inElem_V_10_fu_454_p3 = ((icmp_ln321_2_fu_394_p2[0:0] === 1'b1) ? tmp_V_2_fu_374_p1 : inElem_V_1_fu_204);

assign inElem_V_6_fu_430_p3 = ((or_ln321_fu_400_p2[0:0] === 1'b1) ? inElem_V_3_fu_212 : select_ln321_2_fu_422_p3);

assign inElem_V_7_fu_360_p5 = sf_1_fu_196[1:0];

assign inElem_V_8_fu_438_p3 = ((icmp_ln321_1_fu_388_p2[0:0] === 1'b1) ? tmp_V_2_fu_374_p1 : inElem_V_2_fu_208);

assign inElem_V_9_fu_446_p3 = ((icmp_ln321_2_fu_394_p2[0:0] === 1'b1) ? inElem_V_2_fu_208 : inElem_V_8_fu_438_p3);

assign inElem_V_fu_414_p3 = ((or_ln321_fu_400_p2[0:0] === 1'b1) ? inElem_V_4_fu_216 : select_ln321_fu_406_p3);

assign mul_ln1352_10_fu_1171_p0 = mul_ln1352_10_fu_1171_p00;

assign mul_ln1352_10_fu_1171_p00 = arg_V_read_assign_s_fu_1153_p4;

assign mul_ln1352_11_fu_1199_p0 = mul_ln1352_11_fu_1199_p00;

assign mul_ln1352_11_fu_1199_p00 = arg_V_read_assign_10_fu_1181_p4;

assign mul_ln1352_12_fu_1227_p0 = mul_ln1352_12_fu_1227_p00;

assign mul_ln1352_12_fu_1227_p00 = arg_V_read_assign_11_fu_1209_p4;

assign mul_ln1352_13_fu_1255_p0 = mul_ln1352_13_fu_1255_p00;

assign mul_ln1352_13_fu_1255_p00 = arg_V_read_assign_12_fu_1237_p4;

assign mul_ln1352_14_fu_1283_p0 = mul_ln1352_14_fu_1283_p00;

assign mul_ln1352_14_fu_1283_p00 = arg_V_read_assign_13_fu_1265_p4;

assign mul_ln1352_15_fu_1311_p0 = mul_ln1352_15_fu_1311_p00;

assign mul_ln1352_15_fu_1311_p00 = arg_V_read_assign_14_fu_1293_p4;

assign mul_ln1352_16_fu_1339_p0 = mul_ln1352_16_fu_1339_p00;

assign mul_ln1352_16_fu_1339_p00 = arg_V_read_assign_15_fu_1321_p4;

assign mul_ln1352_17_fu_1367_p0 = mul_ln1352_17_fu_1367_p00;

assign mul_ln1352_17_fu_1367_p00 = arg_V_read_assign_16_fu_1349_p4;

assign mul_ln1352_18_fu_1395_p0 = mul_ln1352_18_fu_1395_p00;

assign mul_ln1352_18_fu_1395_p00 = arg_V_read_assign_17_fu_1377_p4;

assign mul_ln1352_19_fu_1423_p0 = mul_ln1352_19_fu_1423_p00;

assign mul_ln1352_19_fu_1423_p00 = arg_V_read_assign_18_fu_1405_p4;

assign mul_ln1352_1_fu_919_p0 = mul_ln1352_1_fu_919_p00;

assign mul_ln1352_1_fu_919_p00 = arg_V_read_assign_1_fu_901_p4;

assign mul_ln1352_20_fu_1451_p0 = mul_ln1352_20_fu_1451_p00;

assign mul_ln1352_20_fu_1451_p00 = arg_V_read_assign_19_fu_1433_p4;

assign mul_ln1352_21_fu_1479_p0 = mul_ln1352_21_fu_1479_p00;

assign mul_ln1352_21_fu_1479_p00 = arg_V_read_assign_20_fu_1461_p4;

assign mul_ln1352_22_fu_1507_p0 = mul_ln1352_22_fu_1507_p00;

assign mul_ln1352_22_fu_1507_p00 = arg_V_read_assign_21_fu_1489_p4;

assign mul_ln1352_23_fu_1535_p0 = mul_ln1352_23_fu_1535_p00;

assign mul_ln1352_23_fu_1535_p00 = arg_V_read_assign_22_fu_1517_p4;

assign mul_ln1352_24_fu_1563_p0 = mul_ln1352_24_fu_1563_p00;

assign mul_ln1352_24_fu_1563_p00 = arg_V_read_assign_23_fu_1545_p4;

assign mul_ln1352_25_fu_1591_p0 = mul_ln1352_25_fu_1591_p00;

assign mul_ln1352_25_fu_1591_p00 = arg_V_read_assign_24_fu_1573_p4;

assign mul_ln1352_26_fu_1619_p0 = mul_ln1352_26_fu_1619_p00;

assign mul_ln1352_26_fu_1619_p00 = arg_V_read_assign_25_fu_1601_p4;

assign mul_ln1352_27_fu_1647_p0 = mul_ln1352_27_fu_1647_p00;

assign mul_ln1352_27_fu_1647_p00 = arg_V_read_assign_26_fu_1629_p4;

assign mul_ln1352_28_fu_1675_p0 = mul_ln1352_28_fu_1675_p00;

assign mul_ln1352_28_fu_1675_p00 = arg_V_read_assign_27_fu_1657_p4;

assign mul_ln1352_29_fu_1703_p0 = mul_ln1352_29_fu_1703_p00;

assign mul_ln1352_29_fu_1703_p00 = arg_V_read_assign_28_fu_1685_p4;

assign mul_ln1352_2_fu_947_p0 = mul_ln1352_2_fu_947_p00;

assign mul_ln1352_2_fu_947_p00 = arg_V_read_assign_2_fu_929_p4;

assign mul_ln1352_3_fu_975_p0 = mul_ln1352_3_fu_975_p00;

assign mul_ln1352_3_fu_975_p00 = arg_V_read_assign_3_fu_957_p4;

assign mul_ln1352_4_fu_1003_p0 = mul_ln1352_4_fu_1003_p00;

assign mul_ln1352_4_fu_1003_p00 = arg_V_read_assign_4_fu_985_p4;

assign mul_ln1352_5_fu_1031_p0 = mul_ln1352_5_fu_1031_p00;

assign mul_ln1352_5_fu_1031_p00 = arg_V_read_assign_5_fu_1013_p4;

assign mul_ln1352_6_fu_1059_p0 = mul_ln1352_6_fu_1059_p00;

assign mul_ln1352_6_fu_1059_p00 = arg_V_read_assign_6_fu_1041_p4;

assign mul_ln1352_7_fu_1087_p0 = mul_ln1352_7_fu_1087_p00;

assign mul_ln1352_7_fu_1087_p00 = arg_V_read_assign_7_fu_1069_p4;

assign mul_ln1352_8_fu_1115_p0 = mul_ln1352_8_fu_1115_p00;

assign mul_ln1352_8_fu_1115_p00 = arg_V_read_assign_8_fu_1097_p4;

assign mul_ln1352_9_fu_1143_p0 = mul_ln1352_9_fu_1143_p00;

assign mul_ln1352_9_fu_1143_p00 = arg_V_read_assign_9_fu_1125_p4;

assign mul_ln1352_fu_891_p0 = mul_ln1352_fu_891_p00;

assign mul_ln1352_fu_891_p00 = trunc_ln647_fu_879_p1;

assign nf_1_fu_549_p3 = ((icmp_ln173_fu_543_p2[0:0] === 1'b1) ? 32'd0 : nf_fu_537_p2);

assign nf_fu_537_p2 = (nf_assign_fu_200 + 32'd1);

assign or_ln321_fu_400_p2 = (icmp_ln321_2_fu_394_p2 | icmp_ln321_1_fu_388_p2);

assign out_V_V_TDATA = tmp_V_fu_2066_p2;

assign res_V_fu_578_p3 = ((icmp_ln137_reg_2154[0:0] === 1'b1) ? 10'd0 : accu_V_0_0_0_fu_188);

assign select_ln321_2_fu_422_p3 = ((icmp_ln321_fu_382_p2[0:0] === 1'b1) ? tmp_V_2_fu_374_p1 : inElem_V_3_fu_212);

assign select_ln321_fu_406_p3 = ((icmp_ln321_fu_382_p2[0:0] === 1'b1) ? inElem_V_4_fu_216 : tmp_V_2_fu_374_p1);

assign sext_ln170_10_fu_1177_p1 = mul_ln1352_10_fu_1171_p2;

assign sext_ln170_11_fu_1205_p1 = mul_ln1352_11_fu_1199_p2;

assign sext_ln170_12_fu_1233_p1 = mul_ln1352_12_fu_1227_p2;

assign sext_ln170_13_fu_1261_p1 = mul_ln1352_13_fu_1255_p2;

assign sext_ln170_14_fu_1289_p1 = mul_ln1352_14_fu_1283_p2;

assign sext_ln170_15_fu_1317_p1 = mul_ln1352_15_fu_1311_p2;

assign sext_ln170_16_fu_1345_p1 = mul_ln1352_16_fu_1339_p2;

assign sext_ln170_17_fu_1373_p1 = mul_ln1352_17_fu_1367_p2;

assign sext_ln170_18_fu_1401_p1 = mul_ln1352_18_fu_1395_p2;

assign sext_ln170_19_fu_1429_p1 = mul_ln1352_19_fu_1423_p2;

assign sext_ln170_1_fu_925_p1 = mul_ln1352_1_fu_919_p2;

assign sext_ln170_20_fu_1457_p1 = mul_ln1352_20_fu_1451_p2;

assign sext_ln170_21_fu_1485_p1 = mul_ln1352_21_fu_1479_p2;

assign sext_ln170_22_fu_1513_p1 = mul_ln1352_22_fu_1507_p2;

assign sext_ln170_23_fu_1541_p1 = mul_ln1352_23_fu_1535_p2;

assign sext_ln170_24_fu_1569_p1 = mul_ln1352_24_fu_1563_p2;

assign sext_ln170_25_fu_1597_p1 = mul_ln1352_25_fu_1591_p2;

assign sext_ln170_26_fu_1625_p1 = mul_ln1352_26_fu_1619_p2;

assign sext_ln170_27_fu_1653_p1 = mul_ln1352_27_fu_1647_p2;

assign sext_ln170_28_fu_1681_p1 = mul_ln1352_28_fu_1675_p2;

assign sext_ln170_2_fu_953_p1 = mul_ln1352_2_fu_947_p2;

assign sext_ln170_3_fu_981_p1 = mul_ln1352_3_fu_975_p2;

assign sext_ln170_4_fu_1009_p1 = mul_ln1352_4_fu_1003_p2;

assign sext_ln170_5_fu_1037_p1 = mul_ln1352_5_fu_1031_p2;

assign sext_ln170_6_fu_1065_p1 = mul_ln1352_6_fu_1059_p2;

assign sext_ln170_7_fu_1093_p1 = mul_ln1352_7_fu_1087_p2;

assign sext_ln170_8_fu_1121_p1 = mul_ln1352_8_fu_1115_p2;

assign sext_ln170_9_fu_1149_p1 = mul_ln1352_9_fu_1143_p2;

assign sext_ln170_fu_897_p1 = mul_ln1352_fu_891_p2;

assign sext_ln186_fu_2020_p1 = $signed(threshs_m_thresholds_6_reg_2195);

assign sext_ln700_10_fu_1821_p1 = $signed(add_ln700_11_fu_1815_p2);

assign sext_ln700_11_fu_1831_p1 = $signed(add_ln700_12_fu_1825_p2);

assign sext_ln700_12_fu_1847_p1 = $signed(add_ln700_14_fu_1841_p2);

assign sext_ln700_13_fu_1857_p1 = $signed(add_ln700_15_fu_1851_p2);

assign sext_ln700_14_fu_1867_p1 = $signed(add_ln700_16_fu_1861_p2);

assign sext_ln700_15_fu_1877_p1 = $signed(add_ln700_17_fu_1871_p2);

assign sext_ln700_16_fu_1887_p1 = $signed(add_ln700_18_fu_1881_p2);

assign sext_ln700_17_fu_1897_p1 = $signed(add_ln700_19_fu_1891_p2);

assign sext_ln700_18_fu_1907_p1 = $signed(add_ln700_20_fu_1901_p2);

assign sext_ln700_19_fu_1917_p1 = $signed(add_ln700_21_fu_1911_p2);

assign sext_ln700_1_fu_1719_p1 = $signed(add_ln700_fu_1713_p2);

assign sext_ln700_20_fu_1927_p1 = $signed(add_ln700_22_fu_1921_p2);

assign sext_ln700_21_fu_1937_p1 = $signed(add_ln700_23_fu_1931_p2);

assign sext_ln700_22_fu_1947_p1 = $signed(add_ln700_24_fu_1941_p2);

assign sext_ln700_23_fu_1957_p1 = $signed(add_ln700_25_fu_1951_p2);

assign sext_ln700_24_fu_1967_p1 = $signed(add_ln700_26_fu_1961_p2);

assign sext_ln700_25_fu_1977_p1 = $signed(add_ln700_27_fu_1971_p2);

assign sext_ln700_26_fu_1987_p1 = $signed(add_ln700_28_fu_1981_p2);

assign sext_ln700_2_fu_1735_p1 = $signed(add_ln700_2_fu_1729_p2);

assign sext_ln700_3_fu_1745_p1 = $signed(add_ln700_3_fu_1739_p2);

assign sext_ln700_4_fu_1755_p1 = $signed(add_ln700_4_fu_1749_p2);

assign sext_ln700_5_fu_1771_p1 = $signed(add_ln700_6_fu_1765_p2);

assign sext_ln700_6_fu_1781_p1 = $signed(add_ln700_7_fu_1775_p2);

assign sext_ln700_7_fu_1791_p1 = $signed(add_ln700_8_fu_1785_p2);

assign sext_ln700_8_fu_1801_p1 = $signed(add_ln700_9_fu_1795_p2);

assign sext_ln700_9_fu_1811_p1 = $signed(add_ln700_10_fu_1805_p2);

assign sext_ln700_fu_1709_p1 = mul_ln1352_29_fu_1703_p2;

assign sf_fu_505_p2 = (32'd1 + sf_1_fu_196);

assign threshs_m_thresholds_1_address0 = zext_ln186_fu_530_p1;

assign threshs_m_thresholds_2_address0 = zext_ln186_fu_530_p1;

assign threshs_m_thresholds_address0 = zext_ln186_fu_530_p1;

assign tile_1_fu_557_p3 = ((icmp_ln173_fu_543_p2[0:0] === 1'b1) ? 32'd0 : tile_fu_499_p2);

assign tile_fu_499_p2 = (32'd1 + tile_assign_fu_192);

assign tmp_V_2_fu_374_p1 = in_V_V_TDATA[59:0];

assign tmp_V_fu_2066_p2 = (add_ln700_30_fu_2060_p2 + zext_ln700_fu_2016_p1);

assign trunc_ln321_fu_378_p1 = sf_1_fu_196[1:0];

assign trunc_ln647_fu_879_p1 = ap_phi_reg_pp0_iter1_act_m_val_V_reg_296[1:0];

assign weights_m_weights_V_address0 = zext_ln137_fu_494_p1;

assign wgt_M_instance_0_V_fu_585_p1 = weights_m_weights_V_q0[1:0];

assign wgt_M_instance_10_s_fu_679_p4 = {{weights_m_weights_V_q0[21:20]}};

assign wgt_M_instance_11_s_fu_689_p4 = {{weights_m_weights_V_q0[23:22]}};

assign wgt_M_instance_12_s_fu_699_p4 = {{weights_m_weights_V_q0[25:24]}};

assign wgt_M_instance_13_s_fu_709_p4 = {{weights_m_weights_V_q0[27:26]}};

assign wgt_M_instance_14_s_fu_719_p4 = {{weights_m_weights_V_q0[29:28]}};

assign wgt_M_instance_15_s_fu_729_p4 = {{weights_m_weights_V_q0[31:30]}};

assign wgt_M_instance_16_s_fu_739_p4 = {{weights_m_weights_V_q0[33:32]}};

assign wgt_M_instance_17_s_fu_749_p4 = {{weights_m_weights_V_q0[35:34]}};

assign wgt_M_instance_18_s_fu_759_p4 = {{weights_m_weights_V_q0[37:36]}};

assign wgt_M_instance_19_s_fu_769_p4 = {{weights_m_weights_V_q0[39:38]}};

assign wgt_M_instance_1_V_fu_589_p4 = {{weights_m_weights_V_q0[3:2]}};

assign wgt_M_instance_20_s_fu_779_p4 = {{weights_m_weights_V_q0[41:40]}};

assign wgt_M_instance_21_s_fu_789_p4 = {{weights_m_weights_V_q0[43:42]}};

assign wgt_M_instance_22_s_fu_799_p4 = {{weights_m_weights_V_q0[45:44]}};

assign wgt_M_instance_23_s_fu_809_p4 = {{weights_m_weights_V_q0[47:46]}};

assign wgt_M_instance_24_s_fu_819_p4 = {{weights_m_weights_V_q0[49:48]}};

assign wgt_M_instance_25_s_fu_829_p4 = {{weights_m_weights_V_q0[51:50]}};

assign wgt_M_instance_26_s_fu_839_p4 = {{weights_m_weights_V_q0[53:52]}};

assign wgt_M_instance_27_s_fu_849_p4 = {{weights_m_weights_V_q0[55:54]}};

assign wgt_M_instance_28_s_fu_859_p4 = {{weights_m_weights_V_q0[57:56]}};

assign wgt_M_instance_29_s_fu_869_p4 = {{weights_m_weights_V_q0[59:58]}};

assign wgt_M_instance_2_V_fu_599_p4 = {{weights_m_weights_V_q0[5:4]}};

assign wgt_M_instance_3_V_fu_609_p4 = {{weights_m_weights_V_q0[7:6]}};

assign wgt_M_instance_4_V_fu_619_p4 = {{weights_m_weights_V_q0[9:8]}};

assign wgt_M_instance_5_V_fu_629_p4 = {{weights_m_weights_V_q0[11:10]}};

assign wgt_M_instance_6_V_fu_639_p4 = {{weights_m_weights_V_q0[13:12]}};

assign wgt_M_instance_7_V_fu_649_p4 = {{weights_m_weights_V_q0[15:14]}};

assign wgt_M_instance_8_V_fu_659_p4 = {{weights_m_weights_V_q0[17:16]}};

assign wgt_M_instance_9_V_fu_669_p4 = {{weights_m_weights_V_q0[19:18]}};

assign xor_ln899_1_fu_2032_p2 = (icmp_ln899_1_fu_2027_p2 ^ 1'd1);

assign xor_ln899_2_fu_2050_p2 = (icmp_ln899_2_fu_2045_p2 ^ 1'd1);

assign xor_ln899_fu_2010_p2 = (icmp_ln899_fu_2005_p2 ^ 1'd1);

assign zext_ln137_fu_494_p1 = tile_assign_fu_192;

assign zext_ln186_1_fu_2002_p1 = threshs_m_thresholds_4_reg_2190;

assign zext_ln186_2_fu_2023_p1 = $unsigned(sext_ln186_fu_2020_p1);

assign zext_ln186_3_fu_2042_p1 = threshs_m_thresholds_8_reg_2200;

assign zext_ln186_fu_530_p1 = nf_assign_fu_200;

assign zext_ln700_1_fu_2038_p1 = xor_ln899_1_fu_2032_p2;

assign zext_ln700_2_fu_2056_p1 = xor_ln899_2_fu_2050_p2;

assign zext_ln700_fu_2016_p1 = xor_ln899_fu_2010_p2;

endmodule //StreamingFCLayer_Batch_3_Matrix_Vector_Activa
