// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingMaxPool_Batch_0_StreamingMaxPool_Pre (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [31:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg out_V_V_TVALID;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_state5;
reg    out_V_V_TDATA_blk_n;
wire    ap_CS_fsm_state8;
wire   [3:0] i_fu_718_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln153_fu_744_p2;
wire    ap_CS_fsm_state3;
wire   [3:0] yp_fu_750_p2;
reg   [3:0] yp_reg_1212;
wire   [5:0] add_ln154_fu_762_p2;
reg   [5:0] add_ln154_reg_1220;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln155_fu_768_p2;
reg   [0:0] icmp_ln155_reg_1225;
wire   [0:0] icmp_ln154_fu_756_p2;
wire   [0:0] and_ln155_fu_794_p2;
reg   [0:0] and_ln155_reg_1231;
wire   [3:0] select_ln165_fu_806_p3;
reg   [3:0] select_ln165_reg_1236;
reg   [3:0] buf_0_V_addr_2_reg_1241;
reg   [3:0] buf_1_V_addr_2_reg_1246;
reg   [3:0] buf_2_V_addr_2_reg_1251;
reg   [3:0] buf_3_V_addr_2_reg_1256;
reg   [3:0] buf_4_V_addr_2_reg_1261;
reg   [3:0] buf_5_V_addr_2_reg_1266;
reg   [3:0] buf_6_V_addr_2_reg_1271;
reg   [3:0] buf_7_V_addr_2_reg_1276;
reg   [3:0] buf_8_V_addr_2_reg_1281;
reg   [3:0] buf_9_V_addr_2_reg_1286;
reg   [3:0] buf_10_V_addr_2_reg_1291;
reg   [3:0] buf_11_V_addr_2_reg_1296;
reg   [3:0] buf_12_V_addr_2_reg_1301;
reg   [3:0] buf_13_V_addr_2_reg_1306;
reg   [3:0] buf_14_V_addr_2_reg_1311;
reg   [3:0] buf_15_V_addr_2_reg_1316;
wire   [1:0] kx_fu_1110_p3;
wire   [5:0] select_ln155_1_fu_1124_p3;
wire   [3:0] outpix_fu_1137_p2;
reg   [3:0] outpix_reg_1382;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln173_fu_1131_p2;
reg   [3:0] buf_0_V_address0;
reg    buf_0_V_ce0;
reg    buf_0_V_we0;
reg   [1:0] buf_0_V_d0;
wire   [1:0] buf_0_V_q0;
reg   [3:0] buf_1_V_address0;
reg    buf_1_V_ce0;
reg    buf_1_V_we0;
reg   [1:0] buf_1_V_d0;
wire   [1:0] buf_1_V_q0;
reg   [3:0] buf_2_V_address0;
reg    buf_2_V_ce0;
reg    buf_2_V_we0;
reg   [1:0] buf_2_V_d0;
wire   [1:0] buf_2_V_q0;
reg   [3:0] buf_3_V_address0;
reg    buf_3_V_ce0;
reg    buf_3_V_we0;
reg   [1:0] buf_3_V_d0;
wire   [1:0] buf_3_V_q0;
reg   [3:0] buf_4_V_address0;
reg    buf_4_V_ce0;
reg    buf_4_V_we0;
reg   [1:0] buf_4_V_d0;
wire   [1:0] buf_4_V_q0;
reg   [3:0] buf_5_V_address0;
reg    buf_5_V_ce0;
reg    buf_5_V_we0;
reg   [1:0] buf_5_V_d0;
wire   [1:0] buf_5_V_q0;
reg   [3:0] buf_6_V_address0;
reg    buf_6_V_ce0;
reg    buf_6_V_we0;
reg   [1:0] buf_6_V_d0;
wire   [1:0] buf_6_V_q0;
reg   [3:0] buf_7_V_address0;
reg    buf_7_V_ce0;
reg    buf_7_V_we0;
reg   [1:0] buf_7_V_d0;
wire   [1:0] buf_7_V_q0;
reg   [3:0] buf_8_V_address0;
reg    buf_8_V_ce0;
reg    buf_8_V_we0;
reg   [1:0] buf_8_V_d0;
wire   [1:0] buf_8_V_q0;
reg   [3:0] buf_9_V_address0;
reg    buf_9_V_ce0;
reg    buf_9_V_we0;
reg   [1:0] buf_9_V_d0;
wire   [1:0] buf_9_V_q0;
reg   [3:0] buf_10_V_address0;
reg    buf_10_V_ce0;
reg    buf_10_V_we0;
reg   [1:0] buf_10_V_d0;
wire   [1:0] buf_10_V_q0;
reg   [3:0] buf_11_V_address0;
reg    buf_11_V_ce0;
reg    buf_11_V_we0;
reg   [1:0] buf_11_V_d0;
wire   [1:0] buf_11_V_q0;
reg   [3:0] buf_12_V_address0;
reg    buf_12_V_ce0;
reg    buf_12_V_we0;
reg   [1:0] buf_12_V_d0;
wire   [1:0] buf_12_V_q0;
reg   [3:0] buf_13_V_address0;
reg    buf_13_V_ce0;
reg    buf_13_V_we0;
reg   [1:0] buf_13_V_d0;
wire   [1:0] buf_13_V_q0;
reg   [3:0] buf_14_V_address0;
reg    buf_14_V_ce0;
reg    buf_14_V_we0;
reg   [1:0] buf_14_V_d0;
wire   [1:0] buf_14_V_q0;
reg   [3:0] buf_15_V_address0;
reg    buf_15_V_ce0;
reg    buf_15_V_we0;
reg   [1:0] buf_15_V_d0;
wire   [1:0] buf_15_V_q0;
reg   [3:0] i_0_reg_633;
wire   [0:0] icmp_ln146_fu_712_p2;
reg   [3:0] yp_0_reg_644;
reg   [5:0] indvar_flatten45_reg_655;
reg   [5:0] indvar_flatten_reg_666;
reg   [3:0] xp_0_reg_678;
reg   [1:0] kx_0_reg_689;
reg   [3:0] outpix_0_reg_701;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln149_fu_724_p1;
wire   [63:0] zext_ln165_fu_814_p1;
wire   [63:0] zext_ln178_fu_1143_p1;
wire   [0:0] icmp_ln895_fu_839_p2;
wire   [1:0] trunc_ln647_fu_834_p1;
wire   [0:0] icmp_ln895_1_fu_856_p2;
wire   [1:0] p_Result_1_fu_845_p4;
wire   [0:0] icmp_ln895_2_fu_873_p2;
wire   [1:0] p_Result_s_fu_862_p4;
wire   [0:0] icmp_ln895_3_fu_890_p2;
wire   [1:0] p_Result_3_fu_879_p4;
wire   [0:0] icmp_ln895_4_fu_907_p2;
wire   [1:0] p_Result_4_fu_896_p4;
wire   [0:0] icmp_ln895_5_fu_924_p2;
wire   [1:0] p_Result_5_fu_913_p4;
wire   [0:0] icmp_ln895_6_fu_941_p2;
wire   [1:0] p_Result_6_fu_930_p4;
wire   [0:0] icmp_ln895_7_fu_958_p2;
wire   [1:0] p_Result_7_fu_947_p4;
wire   [0:0] icmp_ln895_8_fu_975_p2;
wire   [1:0] p_Result_8_fu_964_p4;
wire   [0:0] icmp_ln895_9_fu_992_p2;
wire   [1:0] p_Result_9_fu_981_p4;
wire   [0:0] icmp_ln895_10_fu_1009_p2;
wire   [1:0] p_Result_2_fu_998_p4;
wire   [0:0] icmp_ln895_11_fu_1026_p2;
wire   [1:0] p_Result_10_fu_1015_p4;
wire   [0:0] icmp_ln895_12_fu_1043_p2;
wire   [1:0] p_Result_11_fu_1032_p4;
wire   [0:0] icmp_ln895_13_fu_1060_p2;
wire   [1:0] p_Result_12_fu_1049_p4;
wire   [0:0] icmp_ln895_14_fu_1077_p2;
wire   [1:0] p_Result_13_fu_1066_p4;
wire   [0:0] icmp_ln895_15_fu_1094_p2;
wire   [1:0] p_Result_14_fu_1083_p4;
wire   [0:0] icmp_ln157_fu_788_p2;
wire   [0:0] xor_ln155_fu_782_p2;
wire   [3:0] select_ln155_fu_774_p3;
wire   [3:0] xp_fu_800_p2;
wire   [0:0] or_ln157_fu_1106_p2;
wire   [1:0] add_ln157_fu_1100_p2;
wire   [5:0] add_ln155_1_fu_1118_p2;
reg   [7:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_0_V_address0),
    .ce0(buf_0_V_ce0),
    .we0(buf_0_V_we0),
    .d0(buf_0_V_d0),
    .q0(buf_0_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_1_V_address0),
    .ce0(buf_1_V_ce0),
    .we0(buf_1_V_we0),
    .d0(buf_1_V_d0),
    .q0(buf_1_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_2_V_address0),
    .ce0(buf_2_V_ce0),
    .we0(buf_2_V_we0),
    .d0(buf_2_V_d0),
    .q0(buf_2_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_3_V_address0),
    .ce0(buf_3_V_ce0),
    .we0(buf_3_V_we0),
    .d0(buf_3_V_d0),
    .q0(buf_3_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_4_V_address0),
    .ce0(buf_4_V_ce0),
    .we0(buf_4_V_we0),
    .d0(buf_4_V_d0),
    .q0(buf_4_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_5_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_5_V_address0),
    .ce0(buf_5_V_ce0),
    .we0(buf_5_V_we0),
    .d0(buf_5_V_d0),
    .q0(buf_5_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_6_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_6_V_address0),
    .ce0(buf_6_V_ce0),
    .we0(buf_6_V_we0),
    .d0(buf_6_V_d0),
    .q0(buf_6_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_7_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_7_V_address0),
    .ce0(buf_7_V_ce0),
    .we0(buf_7_V_we0),
    .d0(buf_7_V_d0),
    .q0(buf_7_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_8_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_8_V_address0),
    .ce0(buf_8_V_ce0),
    .we0(buf_8_V_we0),
    .d0(buf_8_V_d0),
    .q0(buf_8_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_9_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_9_V_address0),
    .ce0(buf_9_V_ce0),
    .we0(buf_9_V_we0),
    .d0(buf_9_V_d0),
    .q0(buf_9_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_10_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_10_V_address0),
    .ce0(buf_10_V_ce0),
    .we0(buf_10_V_we0),
    .d0(buf_10_V_d0),
    .q0(buf_10_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_11_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_11_V_address0),
    .ce0(buf_11_V_ce0),
    .we0(buf_11_V_we0),
    .d0(buf_11_V_d0),
    .q0(buf_11_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_12_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_12_V_address0),
    .ce0(buf_12_V_ce0),
    .we0(buf_12_V_we0),
    .d0(buf_12_V_d0),
    .q0(buf_12_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_13_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_13_V_address0),
    .ce0(buf_13_V_ce0),
    .we0(buf_13_V_we0),
    .d0(buf_13_V_d0),
    .q0(buf_13_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_14_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_14_V_address0),
    .ce0(buf_14_V_ce0),
    .we0(buf_14_V_we0),
    .d0(buf_14_V_d0),
    .q0(buf_14_V_q0)
);

StreamingMaxPool_Batch_0_StreamingMaxPool_bkb #(
    .DataWidth( 2 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
buf_15_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_15_V_address0),
    .ce0(buf_15_V_ce0),
    .we0(buf_15_V_we0),
    .d0(buf_15_V_d0),
    .q0(buf_15_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_0_reg_633 <= i_fu_718_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_633 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln153_fu_744_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        indvar_flatten45_reg_655 <= 6'd0;
    end else if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        indvar_flatten45_reg_655 <= add_ln154_reg_1220;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln153_fu_744_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        indvar_flatten_reg_666 <= 6'd0;
    end else if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        indvar_flatten_reg_666 <= select_ln155_1_fu_1124_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln153_fu_744_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        kx_0_reg_689 <= 2'd0;
    end else if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        kx_0_reg_689 <= kx_fu_1110_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        outpix_0_reg_701 <= 4'd0;
    end else if (((out_V_V_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        outpix_0_reg_701 <= outpix_reg_1382;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln153_fu_744_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        xp_0_reg_678 <= 4'd0;
    end else if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        xp_0_reg_678 <= select_ln165_reg_1236;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln146_fu_712_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        yp_0_reg_644 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln173_fu_1131_p2 == 1'd1))) begin
        yp_0_reg_644 <= yp_reg_1212;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln154_reg_1220 <= add_ln154_fu_762_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln154_fu_756_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        and_ln155_reg_1231 <= and_ln155_fu_794_p2;
        buf_0_V_addr_2_reg_1241 <= zext_ln165_fu_814_p1;
        buf_10_V_addr_2_reg_1291 <= zext_ln165_fu_814_p1;
        buf_11_V_addr_2_reg_1296 <= zext_ln165_fu_814_p1;
        buf_12_V_addr_2_reg_1301 <= zext_ln165_fu_814_p1;
        buf_13_V_addr_2_reg_1306 <= zext_ln165_fu_814_p1;
        buf_14_V_addr_2_reg_1311 <= zext_ln165_fu_814_p1;
        buf_15_V_addr_2_reg_1316 <= zext_ln165_fu_814_p1;
        buf_1_V_addr_2_reg_1246 <= zext_ln165_fu_814_p1;
        buf_2_V_addr_2_reg_1251 <= zext_ln165_fu_814_p1;
        buf_3_V_addr_2_reg_1256 <= zext_ln165_fu_814_p1;
        buf_4_V_addr_2_reg_1261 <= zext_ln165_fu_814_p1;
        buf_5_V_addr_2_reg_1266 <= zext_ln165_fu_814_p1;
        buf_6_V_addr_2_reg_1271 <= zext_ln165_fu_814_p1;
        buf_7_V_addr_2_reg_1276 <= zext_ln165_fu_814_p1;
        buf_8_V_addr_2_reg_1281 <= zext_ln165_fu_814_p1;
        buf_9_V_addr_2_reg_1286 <= zext_ln165_fu_814_p1;
        icmp_ln155_reg_1225 <= icmp_ln155_fu_768_p2;
        select_ln165_reg_1236 <= select_ln165_fu_806_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        outpix_reg_1382 <= outpix_fu_1137_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        yp_reg_1212 <= yp_fu_750_p2;
    end
end

always @ (*) begin
    if ((((icmp_ln153_fu_744_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln153_fu_744_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_0_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_0_V_address0 = buf_0_V_addr_2_reg_1241;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_0_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_0_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_0_V_ce0 = 1'b1;
    end else begin
        buf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_0_V_d0 = trunc_ln647_fu_834_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_0_V_d0 = 2'd0;
    end else begin
        buf_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_fu_839_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_0_V_we0 = 1'b1;
    end else begin
        buf_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_10_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_10_V_address0 = buf_10_V_addr_2_reg_1291;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_10_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_10_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_10_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_10_V_ce0 = 1'b1;
    end else begin
        buf_10_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_10_V_d0 = {{in_V_V_TDATA[21:20]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_10_V_d0 = 2'd0;
    end else begin
        buf_10_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_10_fu_1009_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_10_V_we0 = 1'b1;
    end else begin
        buf_10_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_11_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_11_V_address0 = buf_11_V_addr_2_reg_1296;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_11_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_11_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_11_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_11_V_ce0 = 1'b1;
    end else begin
        buf_11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_11_V_d0 = {{in_V_V_TDATA[23:22]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_11_V_d0 = 2'd0;
    end else begin
        buf_11_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_11_fu_1026_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_11_V_we0 = 1'b1;
    end else begin
        buf_11_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_12_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_12_V_address0 = buf_12_V_addr_2_reg_1301;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_12_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_12_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_12_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_12_V_ce0 = 1'b1;
    end else begin
        buf_12_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_12_V_d0 = {{in_V_V_TDATA[25:24]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_12_V_d0 = 2'd0;
    end else begin
        buf_12_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_12_fu_1043_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_12_V_we0 = 1'b1;
    end else begin
        buf_12_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_13_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_13_V_address0 = buf_13_V_addr_2_reg_1306;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_13_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_13_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_13_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_13_V_ce0 = 1'b1;
    end else begin
        buf_13_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_13_V_d0 = {{in_V_V_TDATA[27:26]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_13_V_d0 = 2'd0;
    end else begin
        buf_13_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_13_fu_1060_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_13_V_we0 = 1'b1;
    end else begin
        buf_13_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_14_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_14_V_address0 = buf_14_V_addr_2_reg_1311;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_14_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_14_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_14_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_14_V_ce0 = 1'b1;
    end else begin
        buf_14_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_14_V_d0 = {{in_V_V_TDATA[29:28]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_14_V_d0 = 2'd0;
    end else begin
        buf_14_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_14_fu_1077_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_14_V_we0 = 1'b1;
    end else begin
        buf_14_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_15_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_15_V_address0 = buf_15_V_addr_2_reg_1316;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_15_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_15_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_15_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_15_V_ce0 = 1'b1;
    end else begin
        buf_15_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_15_V_d0 = {{in_V_V_TDATA[31:30]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_15_V_d0 = 2'd0;
    end else begin
        buf_15_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_15_fu_1094_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_15_V_we0 = 1'b1;
    end else begin
        buf_15_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_1_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_V_address0 = buf_1_V_addr_2_reg_1246;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_1_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_1_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_1_V_ce0 = 1'b1;
    end else begin
        buf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_V_d0 = {{in_V_V_TDATA[3:2]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_1_V_d0 = 2'd0;
    end else begin
        buf_1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_1_fu_856_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_1_V_we0 = 1'b1;
    end else begin
        buf_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_2_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_V_address0 = buf_2_V_addr_2_reg_1251;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_2_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_2_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_2_V_ce0 = 1'b1;
    end else begin
        buf_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_V_d0 = {{in_V_V_TDATA[5:4]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_2_V_d0 = 2'd0;
    end else begin
        buf_2_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_2_fu_873_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_2_V_we0 = 1'b1;
    end else begin
        buf_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_3_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_3_V_address0 = buf_3_V_addr_2_reg_1256;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_3_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_3_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_3_V_ce0 = 1'b1;
    end else begin
        buf_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_3_V_d0 = {{in_V_V_TDATA[7:6]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_3_V_d0 = 2'd0;
    end else begin
        buf_3_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_3_fu_890_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_3_V_we0 = 1'b1;
    end else begin
        buf_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_4_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_4_V_address0 = buf_4_V_addr_2_reg_1261;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_4_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_4_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_4_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_4_V_ce0 = 1'b1;
    end else begin
        buf_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_4_V_d0 = {{in_V_V_TDATA[9:8]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_4_V_d0 = 2'd0;
    end else begin
        buf_4_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_4_fu_907_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_4_V_we0 = 1'b1;
    end else begin
        buf_4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_5_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_5_V_address0 = buf_5_V_addr_2_reg_1266;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_5_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_5_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_5_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_5_V_ce0 = 1'b1;
    end else begin
        buf_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_5_V_d0 = {{in_V_V_TDATA[11:10]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_5_V_d0 = 2'd0;
    end else begin
        buf_5_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_5_fu_924_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_5_V_we0 = 1'b1;
    end else begin
        buf_5_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_6_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_6_V_address0 = buf_6_V_addr_2_reg_1271;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_6_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_6_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_6_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_6_V_ce0 = 1'b1;
    end else begin
        buf_6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_6_V_d0 = {{in_V_V_TDATA[13:12]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_6_V_d0 = 2'd0;
    end else begin
        buf_6_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_6_fu_941_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_6_V_we0 = 1'b1;
    end else begin
        buf_6_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_7_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_7_V_address0 = buf_7_V_addr_2_reg_1276;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_7_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_7_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_7_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_7_V_ce0 = 1'b1;
    end else begin
        buf_7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_7_V_d0 = {{in_V_V_TDATA[15:14]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_7_V_d0 = 2'd0;
    end else begin
        buf_7_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_7_fu_958_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_7_V_we0 = 1'b1;
    end else begin
        buf_7_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_8_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_8_V_address0 = buf_8_V_addr_2_reg_1281;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_8_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_8_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_8_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_8_V_ce0 = 1'b1;
    end else begin
        buf_8_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_8_V_d0 = {{in_V_V_TDATA[17:16]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_8_V_d0 = 2'd0;
    end else begin
        buf_8_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_8_fu_975_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_8_V_we0 = 1'b1;
    end else begin
        buf_8_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        buf_9_V_address0 = zext_ln178_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_9_V_address0 = buf_9_V_addr_2_reg_1286;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_9_V_address0 = zext_ln165_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_9_V_address0 = zext_ln149_fu_724_p1;
    end else begin
        buf_9_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_9_V_ce0 = 1'b1;
    end else begin
        buf_9_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_9_V_d0 = {{in_V_V_TDATA[19:18]}};
    end else if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_9_V_d0 = 2'd0;
    end else begin
        buf_9_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln146_fu_712_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln895_9_fu_992_p2 == 1'd1) & (in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln173_fu_1131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        buf_9_V_we0 = 1'b1;
    end else begin
        buf_9_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_V_V_TDATA_blk_n = in_V_V_TVALID;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        out_V_V_TDATA_blk_n = out_V_V_TREADY;
    end else begin
        out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((out_V_V_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_V_V_TVALID = 1'b1;
    end else begin
        out_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln146_fu_712_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln153_fu_744_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln154_fu_756_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((in_V_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln173_fu_1131_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((out_V_V_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln154_fu_762_p2 = (indvar_flatten45_reg_655 + 6'd1);

assign add_ln155_1_fu_1118_p2 = (indvar_flatten_reg_666 + 6'd1);

assign add_ln157_fu_1100_p2 = (kx_0_reg_689 + 2'd1);

assign and_ln155_fu_794_p2 = (xor_ln155_fu_782_p2 & icmp_ln157_fu_788_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign i_fu_718_p2 = (i_0_reg_633 + 4'd1);

assign icmp_ln146_fu_712_p2 = ((i_0_reg_633 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln153_fu_744_p2 = ((yp_0_reg_644 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_756_p2 = ((indvar_flatten45_reg_655 == 6'd56) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_768_p2 = ((indvar_flatten_reg_666 == 6'd28) ? 1'b1 : 1'b0);

assign icmp_ln157_fu_788_p2 = ((kx_0_reg_689 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln173_fu_1131_p2 = ((outpix_0_reg_701 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln895_10_fu_1009_p2 = ((p_Result_2_fu_998_p4 > buf_10_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_11_fu_1026_p2 = ((p_Result_10_fu_1015_p4 > buf_11_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_12_fu_1043_p2 = ((p_Result_11_fu_1032_p4 > buf_12_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_13_fu_1060_p2 = ((p_Result_12_fu_1049_p4 > buf_13_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_14_fu_1077_p2 = ((p_Result_13_fu_1066_p4 > buf_14_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_15_fu_1094_p2 = ((p_Result_14_fu_1083_p4 > buf_15_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_1_fu_856_p2 = ((p_Result_1_fu_845_p4 > buf_1_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_2_fu_873_p2 = ((p_Result_s_fu_862_p4 > buf_2_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_3_fu_890_p2 = ((p_Result_3_fu_879_p4 > buf_3_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_4_fu_907_p2 = ((p_Result_4_fu_896_p4 > buf_4_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_5_fu_924_p2 = ((p_Result_5_fu_913_p4 > buf_5_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_6_fu_941_p2 = ((p_Result_6_fu_930_p4 > buf_6_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_7_fu_958_p2 = ((p_Result_7_fu_947_p4 > buf_7_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_8_fu_975_p2 = ((p_Result_8_fu_964_p4 > buf_8_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_9_fu_992_p2 = ((p_Result_9_fu_981_p4 > buf_9_V_q0) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_839_p2 = ((trunc_ln647_fu_834_p1 > buf_0_V_q0) ? 1'b1 : 1'b0);

assign kx_fu_1110_p3 = ((or_ln157_fu_1106_p2[0:0] === 1'b1) ? 2'd1 : add_ln157_fu_1100_p2);

assign or_ln157_fu_1106_p2 = (icmp_ln155_reg_1225 | and_ln155_reg_1231);

assign out_V_V_TDATA = {{{{{{{{{{{{{{{{buf_15_V_q0}, {buf_14_V_q0}}, {buf_13_V_q0}}, {buf_12_V_q0}}, {buf_11_V_q0}}, {buf_10_V_q0}}, {buf_9_V_q0}}, {buf_8_V_q0}}, {buf_7_V_q0}}, {buf_6_V_q0}}, {buf_5_V_q0}}, {buf_4_V_q0}}, {buf_3_V_q0}}, {buf_2_V_q0}}, {buf_1_V_q0}}, {buf_0_V_q0}};

assign outpix_fu_1137_p2 = (outpix_0_reg_701 + 4'd1);

assign p_Result_10_fu_1015_p4 = {{in_V_V_TDATA[23:22]}};

assign p_Result_11_fu_1032_p4 = {{in_V_V_TDATA[25:24]}};

assign p_Result_12_fu_1049_p4 = {{in_V_V_TDATA[27:26]}};

assign p_Result_13_fu_1066_p4 = {{in_V_V_TDATA[29:28]}};

assign p_Result_14_fu_1083_p4 = {{in_V_V_TDATA[31:30]}};

assign p_Result_1_fu_845_p4 = {{in_V_V_TDATA[3:2]}};

assign p_Result_2_fu_998_p4 = {{in_V_V_TDATA[21:20]}};

assign p_Result_3_fu_879_p4 = {{in_V_V_TDATA[7:6]}};

assign p_Result_4_fu_896_p4 = {{in_V_V_TDATA[9:8]}};

assign p_Result_5_fu_913_p4 = {{in_V_V_TDATA[11:10]}};

assign p_Result_6_fu_930_p4 = {{in_V_V_TDATA[13:12]}};

assign p_Result_7_fu_947_p4 = {{in_V_V_TDATA[15:14]}};

assign p_Result_8_fu_964_p4 = {{in_V_V_TDATA[17:16]}};

assign p_Result_9_fu_981_p4 = {{in_V_V_TDATA[19:18]}};

assign p_Result_s_fu_862_p4 = {{in_V_V_TDATA[5:4]}};

assign select_ln155_1_fu_1124_p3 = ((icmp_ln155_reg_1225[0:0] === 1'b1) ? 6'd1 : add_ln155_1_fu_1118_p2);

assign select_ln155_fu_774_p3 = ((icmp_ln155_fu_768_p2[0:0] === 1'b1) ? 4'd0 : xp_0_reg_678);

assign select_ln165_fu_806_p3 = ((and_ln155_fu_794_p2[0:0] === 1'b1) ? xp_fu_800_p2 : select_ln155_fu_774_p3);

assign trunc_ln647_fu_834_p1 = in_V_V_TDATA[1:0];

assign xor_ln155_fu_782_p2 = (icmp_ln155_fu_768_p2 ^ 1'd1);

assign xp_fu_800_p2 = (4'd1 + select_ln155_fu_774_p3);

assign yp_fu_750_p2 = (yp_0_reg_644 + 4'd1);

assign zext_ln149_fu_724_p1 = i_0_reg_633;

assign zext_ln165_fu_814_p1 = select_ln165_fu_806_p3;

assign zext_ln178_fu_1143_p1 = outpix_0_reg_701;

endmodule //StreamingMaxPool_Batch_0_StreamingMaxPool_Pre
